/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using APICrawler.Api.Client;
using APICrawler.Api.Api;
// uncomment below to import models
//using APICrawler.Api.Model;

namespace APICrawler.Api.Test.Api
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DefaultApiTests : IDisposable
    {
        private DefaultApi instance;

        public DefaultApiTests()
        {
            instance = new DefaultApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DefaultApi
            //Assert.IsType<DefaultApi>(instance);
        }

        /// <summary>
        /// Test AdresseGet
        /// </summary>
        [Fact]
        public void AdresseGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string adresseNr = null;
            //var response = instance.AdresseGet(adresseNr);
            //Assert.IsType<Adresse>(response);
        }

        /// <summary>
        /// Test AntragGet
        /// </summary>
        [Fact]
        public void AntragGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string antragnr = null;
            //string antragstellerNr = null;
            //string kennr = null;
            //var response = instance.AntragGet(antragnr, antragstellerNr, kennr);
            //Assert.IsType<Antrag>(response);
        }

        /// <summary>
        /// Test AuflageReduGet
        /// </summary>
        [Fact]
        public void AuflageReduGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string auflagenr = null;
            //var response = instance.AuflageReduGet(auflagenr);
            //Assert.IsType<AuflageRedu>(response);
        }

        /// <summary>
        /// Test AuflagenGet
        /// </summary>
        [Fact]
        public void AuflagenGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string auflage = null;
            //string auflagenr = null;
            //string ebene = null;
            //var response = instance.AuflagenGet(auflage, auflagenr, ebene);
            //Assert.IsType<Auflagen>(response);
        }

        /// <summary>
        /// Test AwgAufwandGet
        /// </summary>
        [Fact]
        public void AwgAufwandGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string awgId = null;
            //var response = instance.AwgAufwandGet(awgId);
            //Assert.IsType<AwgAufwand>(response);
        }

        /// <summary>
        /// Test AwgBemGet
        /// </summary>
        [Fact]
        public void AwgBemGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string awgId = null;
            //var response = instance.AwgBemGet(awgId);
            //Assert.IsType<AwgBem>(response);
        }

        /// <summary>
        /// Test AwgGet
        /// </summary>
        [Fact]
        public void AwgGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string awgId = null;
            //string kennr = null;
            //var response = instance.AwgGet(awgId, kennr);
            //Assert.IsType<Awg>(response);
        }

        /// <summary>
        /// Test AwgKulturGet
        /// </summary>
        [Fact]
        public void AwgKulturGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string awgId = null;
            //var response = instance.AwgKulturGet(awgId);
            //Assert.IsType<AwgKultur>(response);
        }

        /// <summary>
        /// Test AwgPartnerAufwandGet
        /// </summary>
        [Fact]
        public void AwgPartnerAufwandGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string awgId = null;
            //var response = instance.AwgPartnerAufwandGet(awgId);
            //Assert.IsType<AwgPartnerAufwand>(response);
        }

        /// <summary>
        /// Test AwgPartnerGet
        /// </summary>
        [Fact]
        public void AwgPartnerGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string awgId = null;
            //var response = instance.AwgPartnerGet(awgId);
            //Assert.IsType<AwgPartner>(response);
        }

        /// <summary>
        /// Test AwgSchadorgGet
        /// </summary>
        [Fact]
        public void AwgSchadorgGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string awgId = null;
            //var response = instance.AwgSchadorgGet(awgId);
            //Assert.IsType<AwgSchadorg>(response);
        }

        /// <summary>
        /// Test AwgVerwendungszweckGet
        /// </summary>
        [Fact]
        public void AwgVerwendungszweckGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string awgId = null;
            //var response = instance.AwgVerwendungszweckGet(awgId);
            //Assert.IsType<AwgVerwendungszweck>(response);
        }

        /// <summary>
        /// Test AwgWartezeitAusgKulturGet
        /// </summary>
        [Fact]
        public void AwgWartezeitAusgKulturGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string awgWartezeitNr = null;
            //string kultur = null;
            //var response = instance.AwgWartezeitAusgKulturGet(awgWartezeitNr, kultur);
            //Assert.IsType<AwgWartezeitAusgKultur>(response);
        }

        /// <summary>
        /// Test AwgWartezeitGet
        /// </summary>
        [Fact]
        public void AwgWartezeitGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string awgId = null;
            //string awgWartezeitNr = null;
            //string kultur = null;
            //var response = instance.AwgWartezeitGet(awgId, awgWartezeitNr, kultur);
            //Assert.IsType<AwgWartezeit>(response);
        }

        /// <summary>
        /// Test AwgZeitpunktGet
        /// </summary>
        [Fact]
        public void AwgZeitpunktGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string awgId = null;
            //var response = instance.AwgZeitpunktGet(awgId);
            //Assert.IsType<AwgZeitpunkt>(response);
        }

        /// <summary>
        /// Test AwgZulassungGet
        /// </summary>
        [Fact]
        public void AwgZulassungGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string awgId = null;
            //var response = instance.AwgZulassungGet(awgId);
            //Assert.IsType<AwgZulassung>(response);
        }

        /// <summary>
        /// Test GhsGefahrenhinweiseGet
        /// </summary>
        [Fact]
        public void GhsGefahrenhinweiseGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kennr = null;
            //var response = instance.GhsGefahrenhinweiseGet(kennr);
            //Assert.IsType<GhsGefahrenhinweise>(response);
        }

        /// <summary>
        /// Test GhsGefahrensymboleGet
        /// </summary>
        [Fact]
        public void GhsGefahrensymboleGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kennr = null;
            //var response = instance.GhsGefahrensymboleGet(kennr);
            //Assert.IsType<GhsGefahrensymbole>(response);
        }

        /// <summary>
        /// Test GhsSicherheitshinweiseGet
        /// </summary>
        [Fact]
        public void GhsSicherheitshinweiseGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kennr = null;
            //var response = instance.GhsSicherheitshinweiseGet(kennr);
            //Assert.IsType<GhsSicherheitshinweise>(response);
        }

        /// <summary>
        /// Test GhsSignalwoerterGet
        /// </summary>
        [Fact]
        public void GhsSignalwoerterGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kennr = null;
            //var response = instance.GhsSignalwoerterGet(kennr);
            //Assert.IsType<GhsSignalwoerter>(response);
        }

        /// <summary>
        /// Test HinweisGet
        /// </summary>
        [Fact]
        public void HinweisGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ebene = null;
            //var response = instance.HinweisGet(ebene);
            //Assert.IsType<Hinweis>(response);
        }

        /// <summary>
        /// Test KodeGet
        /// </summary>
        [Fact]
        public void KodeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kode = null;
            //string kodeliste = null;
            //string sprache = null;
            //var response = instance.KodeGet(kode, kodeliste, sprache);
            //Assert.IsType<Kode>(response);
        }

        /// <summary>
        /// Test KodelisteFeldnameGet
        /// </summary>
        [Fact]
        public void KodelisteFeldnameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string feldname = null;
            //string kodeliste = null;
            //string tabelle = null;
            //var response = instance.KodelisteFeldnameGet(feldname, kodeliste, tabelle);
            //Assert.IsType<KodelisteFeldname>(response);
        }

        /// <summary>
        /// Test KodelisteGet
        /// </summary>
        [Fact]
        public void KodelisteGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kodeliste = null;
            //var response = instance.KodelisteGet(kodeliste);
            //Assert.IsType<Kodeliste>(response);
        }

        /// <summary>
        /// Test KulturGruppeGet
        /// </summary>
        [Fact]
        public void KulturGruppeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kultur = null;
            //string kulturGruppe = null;
            //var response = instance.KulturGruppeGet(kultur, kulturGruppe);
            //Assert.IsType<KulturGruppe>(response);
        }

        /// <summary>
        /// Test MittelAbgelaufenGet
        /// </summary>
        [Fact]
        public void MittelAbgelaufenGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kennr = null;
            //var response = instance.MittelAbgelaufenGet(kennr);
            //Assert.IsType<MittelAbgelaufen>(response);
        }

        /// <summary>
        /// Test MittelAbpackungGet
        /// </summary>
        [Fact]
        public void MittelAbpackungGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kennr = null;
            //var response = instance.MittelAbpackungGet(kennr);
            //Assert.IsType<MittelAbpackung>(response);
        }

        /// <summary>
        /// Test MittelGefahrenSymbolGet
        /// </summary>
        [Fact]
        public void MittelGefahrenSymbolGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kennr = null;
            //var response = instance.MittelGefahrenSymbolGet(kennr);
            //Assert.IsType<MittelGefahrenSymbol>(response);
        }

        /// <summary>
        /// Test MittelGet
        /// </summary>
        [Fact]
        public void MittelGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kennr = null;
            //var response = instance.MittelGet(kennr);
            //Assert.IsType<Mittel>(response);
        }

        /// <summary>
        /// Test MittelVertriebGet
        /// </summary>
        [Fact]
        public void MittelVertriebGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kennr = null;
            //string vertriebsfirmaNr = null;
            //var response = instance.MittelVertriebGet(kennr, vertriebsfirmaNr);
            //Assert.IsType<MittelVertrieb>(response);
        }

        /// <summary>
        /// Test MittelWirkbereichGet
        /// </summary>
        [Fact]
        public void MittelWirkbereichGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kennr = null;
            //string wirkungsbereich = null;
            //var response = instance.MittelWirkbereichGet(kennr, wirkungsbereich);
            //Assert.IsType<MittelWirkbereich>(response);
        }

        /// <summary>
        /// Test ParallelimportAbgelaufenGet
        /// </summary>
        [Fact]
        public void ParallelimportAbgelaufenGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string importeurNr = null;
            //string piReferenzKennr = null;
            //var response = instance.ParallelimportAbgelaufenGet(importeurNr, piReferenzKennr);
            //Assert.IsType<ParallelimportAbgelaufen>(response);
        }

        /// <summary>
        /// Test ParallelimportGueltigGet
        /// </summary>
        [Fact]
        public void ParallelimportGueltigGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string importeurNr = null;
            //string piReferenzKennr = null;
            //var response = instance.ParallelimportGueltigGet(importeurNr, piReferenzKennr);
            //Assert.IsType<ParallelimportGueltig>(response);
        }

        /// <summary>
        /// Test SchadorgGruppeGet
        /// </summary>
        [Fact]
        public void SchadorgGruppeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string schadorg = null;
            //string schadorgGruppe = null;
            //var response = instance.SchadorgGruppeGet(schadorg, schadorgGruppe);
            //Assert.IsType<SchadorgGruppe>(response);
        }

        /// <summary>
        /// Test StaerkungGet
        /// </summary>
        [Fact]
        public void StaerkungGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string antragstellerNr = null;
            //string kennr = null;
            //var response = instance.StaerkungGet(antragstellerNr, kennr);
            //Assert.IsType<Staerkung>(response);
        }

        /// <summary>
        /// Test StaerkungVertriebGet
        /// </summary>
        [Fact]
        public void StaerkungVertriebGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kennr = null;
            //string vertriebsfirmaNr = null;
            //var response = instance.StaerkungVertriebGet(kennr, vertriebsfirmaNr);
            //Assert.IsType<StaerkungVertrieb>(response);
        }

        /// <summary>
        /// Test StandGet
        /// </summary>
        [Fact]
        public void StandGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.StandGet();
            //Assert.IsType<Stand>(response);
        }

        /// <summary>
        /// Test WirkstoffGehaltGet
        /// </summary>
        [Fact]
        public void WirkstoffGehaltGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kennr = null;
            //string wirknr = null;
            //var response = instance.WirkstoffGehaltGet(kennr, wirknr);
            //Assert.IsType<WirkstoffGehalt>(response);
        }

        /// <summary>
        /// Test WirkstoffGet
        /// </summary>
        [Fact]
        public void WirkstoffGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string wirknr = null;
            //var response = instance.WirkstoffGet(wirknr);
            //Assert.IsType<Wirkstoff>(response);
        }

        /// <summary>
        /// Test ZusatzstoffGet
        /// </summary>
        [Fact]
        public void ZusatzstoffGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string antragstellerNr = null;
            //string kennr = null;
            //var response = instance.ZusatzstoffGet(antragstellerNr, kennr);
            //Assert.IsType<Zusatzstoff>(response);
        }

        /// <summary>
        /// Test ZusatzstoffVertriebGet
        /// </summary>
        [Fact]
        public void ZusatzstoffVertriebGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kennr = null;
            //string vertriebsfirmaNr = null;
            //var response = instance.ZusatzstoffVertriebGet(kennr, vertriebsfirmaNr);
            //Assert.IsType<ZusatzstoffVertrieb>(response);
        }
    }
}
