/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// AdresseItems
    /// </summary>
    [DataContract(Name = "Adresse_items")]
    public partial class AdresseItems : IEquatable<AdresseItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdresseItems" /> class.
        /// </summary>
        /// <param name="aDRESSENR">aDRESSENR.</param>
        /// <param name="aNSCHRIFT1">aNSCHRIFT1.</param>
        /// <param name="aNSCHRIFT2">aNSCHRIFT2.</param>
        /// <param name="aNSCHRIFT3">aNSCHRIFT3.</param>
        /// <param name="aNSCHRIFT4">aNSCHRIFT4.</param>
        /// <param name="aNSCHRIFT5">aNSCHRIFT5.</param>
        /// <param name="aNSCHRIFT6">aNSCHRIFT6.</param>
        /// <param name="aNSPRECHPARTNER">aNSPRECHPARTNER.</param>
        /// <param name="eMAIL">eMAIL.</param>
        /// <param name="fAX">fAX.</param>
        /// <param name="fIRMA">fIRMA.</param>
        /// <param name="fIRMENNAME">fIRMENNAME.</param>
        /// <param name="lAND">lAND.</param>
        /// <param name="tELEFON">tELEFON.</param>
        public AdresseItems(string aDRESSENR = default(string), string aNSCHRIFT1 = default(string), string aNSCHRIFT2 = default(string), string aNSCHRIFT3 = default(string), string aNSCHRIFT4 = default(string), string aNSCHRIFT5 = default(string), string aNSCHRIFT6 = default(string), string aNSPRECHPARTNER = default(string), string eMAIL = default(string), string fAX = default(string), string fIRMA = default(string), string fIRMENNAME = default(string), string lAND = default(string), string tELEFON = default(string))
        {
            this.ADRESSE_NR = aDRESSENR;
            this.ANSCHRIFT1 = aNSCHRIFT1;
            this.ANSCHRIFT2 = aNSCHRIFT2;
            this.ANSCHRIFT3 = aNSCHRIFT3;
            this.ANSCHRIFT4 = aNSCHRIFT4;
            this.ANSCHRIFT5 = aNSCHRIFT5;
            this.ANSCHRIFT6 = aNSCHRIFT6;
            this.ANSPRECHPARTNER = aNSPRECHPARTNER;
            this.E_MAIL = eMAIL;
            this.FAX = fAX;
            this.FIRMA = fIRMA;
            this.FIRMENNAME = fIRMENNAME;
            this.LAND = lAND;
            this.TELEFON = tELEFON;
        }

        /// <summary>
        /// Gets or Sets ADRESSE_NR
        /// </summary>
        [DataMember(Name = "ADRESSE_NR", EmitDefaultValue = false)]
        public string ADRESSE_NR { get; set; }

        /// <summary>
        /// Gets or Sets ANSCHRIFT1
        /// </summary>
        [DataMember(Name = "ANSCHRIFT_1", EmitDefaultValue = false)]
        public string ANSCHRIFT1 { get; set; }

        /// <summary>
        /// Gets or Sets ANSCHRIFT2
        /// </summary>
        [DataMember(Name = "ANSCHRIFT_2", EmitDefaultValue = false)]
        public string ANSCHRIFT2 { get; set; }

        /// <summary>
        /// Gets or Sets ANSCHRIFT3
        /// </summary>
        [DataMember(Name = "ANSCHRIFT_3", EmitDefaultValue = false)]
        public string ANSCHRIFT3 { get; set; }

        /// <summary>
        /// Gets or Sets ANSCHRIFT4
        /// </summary>
        [DataMember(Name = "ANSCHRIFT_4", EmitDefaultValue = false)]
        public string ANSCHRIFT4 { get; set; }

        /// <summary>
        /// Gets or Sets ANSCHRIFT5
        /// </summary>
        [DataMember(Name = "ANSCHRIFT_5", EmitDefaultValue = false)]
        public string ANSCHRIFT5 { get; set; }

        /// <summary>
        /// Gets or Sets ANSCHRIFT6
        /// </summary>
        [DataMember(Name = "ANSCHRIFT_6", EmitDefaultValue = false)]
        public string ANSCHRIFT6 { get; set; }

        /// <summary>
        /// Gets or Sets ANSPRECHPARTNER
        /// </summary>
        [DataMember(Name = "ANSPRECHPARTNER", EmitDefaultValue = false)]
        public string ANSPRECHPARTNER { get; set; }

        /// <summary>
        /// Gets or Sets E_MAIL
        /// </summary>
        [DataMember(Name = "E_MAIL", EmitDefaultValue = false)]
        public string E_MAIL { get; set; }

        /// <summary>
        /// Gets or Sets FAX
        /// </summary>
        [DataMember(Name = "FAX", EmitDefaultValue = false)]
        public string FAX { get; set; }

        /// <summary>
        /// Gets or Sets FIRMA
        /// </summary>
        [DataMember(Name = "FIRMA", EmitDefaultValue = false)]
        public string FIRMA { get; set; }

        /// <summary>
        /// Gets or Sets FIRMENNAME
        /// </summary>
        [DataMember(Name = "FIRMENNAME", EmitDefaultValue = false)]
        public string FIRMENNAME { get; set; }

        /// <summary>
        /// Gets or Sets LAND
        /// </summary>
        [DataMember(Name = "LAND", EmitDefaultValue = false)]
        public string LAND { get; set; }

        /// <summary>
        /// Gets or Sets TELEFON
        /// </summary>
        [DataMember(Name = "TELEFON", EmitDefaultValue = false)]
        public string TELEFON { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AdresseItems {\n");
            sb.Append("  ADRESSE_NR: ").Append(ADRESSE_NR).Append("\n");
            sb.Append("  ANSCHRIFT1: ").Append(ANSCHRIFT1).Append("\n");
            sb.Append("  ANSCHRIFT2: ").Append(ANSCHRIFT2).Append("\n");
            sb.Append("  ANSCHRIFT3: ").Append(ANSCHRIFT3).Append("\n");
            sb.Append("  ANSCHRIFT4: ").Append(ANSCHRIFT4).Append("\n");
            sb.Append("  ANSCHRIFT5: ").Append(ANSCHRIFT5).Append("\n");
            sb.Append("  ANSCHRIFT6: ").Append(ANSCHRIFT6).Append("\n");
            sb.Append("  ANSPRECHPARTNER: ").Append(ANSPRECHPARTNER).Append("\n");
            sb.Append("  E_MAIL: ").Append(E_MAIL).Append("\n");
            sb.Append("  FAX: ").Append(FAX).Append("\n");
            sb.Append("  FIRMA: ").Append(FIRMA).Append("\n");
            sb.Append("  FIRMENNAME: ").Append(FIRMENNAME).Append("\n");
            sb.Append("  LAND: ").Append(LAND).Append("\n");
            sb.Append("  TELEFON: ").Append(TELEFON).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AdresseItems);
        }

        /// <summary>
        /// Returns true if AdresseItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AdresseItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AdresseItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ADRESSE_NR == input.ADRESSE_NR ||
                    (this.ADRESSE_NR != null &&
                    this.ADRESSE_NR.Equals(input.ADRESSE_NR))
                ) && 
                (
                    this.ANSCHRIFT1 == input.ANSCHRIFT1 ||
                    (this.ANSCHRIFT1 != null &&
                    this.ANSCHRIFT1.Equals(input.ANSCHRIFT1))
                ) && 
                (
                    this.ANSCHRIFT2 == input.ANSCHRIFT2 ||
                    (this.ANSCHRIFT2 != null &&
                    this.ANSCHRIFT2.Equals(input.ANSCHRIFT2))
                ) && 
                (
                    this.ANSCHRIFT3 == input.ANSCHRIFT3 ||
                    (this.ANSCHRIFT3 != null &&
                    this.ANSCHRIFT3.Equals(input.ANSCHRIFT3))
                ) && 
                (
                    this.ANSCHRIFT4 == input.ANSCHRIFT4 ||
                    (this.ANSCHRIFT4 != null &&
                    this.ANSCHRIFT4.Equals(input.ANSCHRIFT4))
                ) && 
                (
                    this.ANSCHRIFT5 == input.ANSCHRIFT5 ||
                    (this.ANSCHRIFT5 != null &&
                    this.ANSCHRIFT5.Equals(input.ANSCHRIFT5))
                ) && 
                (
                    this.ANSCHRIFT6 == input.ANSCHRIFT6 ||
                    (this.ANSCHRIFT6 != null &&
                    this.ANSCHRIFT6.Equals(input.ANSCHRIFT6))
                ) && 
                (
                    this.ANSPRECHPARTNER == input.ANSPRECHPARTNER ||
                    (this.ANSPRECHPARTNER != null &&
                    this.ANSPRECHPARTNER.Equals(input.ANSPRECHPARTNER))
                ) && 
                (
                    this.E_MAIL == input.E_MAIL ||
                    (this.E_MAIL != null &&
                    this.E_MAIL.Equals(input.E_MAIL))
                ) && 
                (
                    this.FAX == input.FAX ||
                    (this.FAX != null &&
                    this.FAX.Equals(input.FAX))
                ) && 
                (
                    this.FIRMA == input.FIRMA ||
                    (this.FIRMA != null &&
                    this.FIRMA.Equals(input.FIRMA))
                ) && 
                (
                    this.FIRMENNAME == input.FIRMENNAME ||
                    (this.FIRMENNAME != null &&
                    this.FIRMENNAME.Equals(input.FIRMENNAME))
                ) && 
                (
                    this.LAND == input.LAND ||
                    (this.LAND != null &&
                    this.LAND.Equals(input.LAND))
                ) && 
                (
                    this.TELEFON == input.TELEFON ||
                    (this.TELEFON != null &&
                    this.TELEFON.Equals(input.TELEFON))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ADRESSE_NR != null)
                    hashCode = hashCode * 59 + this.ADRESSE_NR.GetHashCode();
                if (this.ANSCHRIFT1 != null)
                    hashCode = hashCode * 59 + this.ANSCHRIFT1.GetHashCode();
                if (this.ANSCHRIFT2 != null)
                    hashCode = hashCode * 59 + this.ANSCHRIFT2.GetHashCode();
                if (this.ANSCHRIFT3 != null)
                    hashCode = hashCode * 59 + this.ANSCHRIFT3.GetHashCode();
                if (this.ANSCHRIFT4 != null)
                    hashCode = hashCode * 59 + this.ANSCHRIFT4.GetHashCode();
                if (this.ANSCHRIFT5 != null)
                    hashCode = hashCode * 59 + this.ANSCHRIFT5.GetHashCode();
                if (this.ANSCHRIFT6 != null)
                    hashCode = hashCode * 59 + this.ANSCHRIFT6.GetHashCode();
                if (this.ANSPRECHPARTNER != null)
                    hashCode = hashCode * 59 + this.ANSPRECHPARTNER.GetHashCode();
                if (this.E_MAIL != null)
                    hashCode = hashCode * 59 + this.E_MAIL.GetHashCode();
                if (this.FAX != null)
                    hashCode = hashCode * 59 + this.FAX.GetHashCode();
                if (this.FIRMA != null)
                    hashCode = hashCode * 59 + this.FIRMA.GetHashCode();
                if (this.FIRMENNAME != null)
                    hashCode = hashCode * 59 + this.FIRMENNAME.GetHashCode();
                if (this.LAND != null)
                    hashCode = hashCode * 59 + this.LAND.GetHashCode();
                if (this.TELEFON != null)
                    hashCode = hashCode * 59 + this.TELEFON.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
