/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// AntragItems
    /// </summary>
    [DataContract(Name = "Antrag_items")]
    public partial class AntragItems : IEquatable<AntragItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AntragItems" /> class.
        /// </summary>
        /// <param name="aNTRAGNR">aNTRAGNR.</param>
        /// <param name="aNTRAGSTELLER">aNTRAGSTELLER.</param>
        /// <param name="aNTRAGSTELLERNR">aNTRAGSTELLERNR.</param>
        /// <param name="kENNR">kENNR.</param>
        /// <param name="mROW">mROW.</param>
        public AntragItems(string aNTRAGNR = default(string), string aNTRAGSTELLER = default(string), string aNTRAGSTELLERNR = default(string), string kENNR = default(string), string mROW = default(string))
        {
            this.ANTRAGNR = aNTRAGNR;
            this.ANTRAGSTELLER = aNTRAGSTELLER;
            this.ANTRAGSTELLER_NR = aNTRAGSTELLERNR;
            this.KENNR = kENNR;
            this.M_ROW = mROW;
        }

        /// <summary>
        /// Gets or Sets ANTRAGNR
        /// </summary>
        [DataMember(Name = "ANTRAGNR", EmitDefaultValue = false)]
        public string ANTRAGNR { get; set; }

        /// <summary>
        /// Gets or Sets ANTRAGSTELLER
        /// </summary>
        [DataMember(Name = "ANTRAGSTELLER", EmitDefaultValue = false)]
        public string ANTRAGSTELLER { get; set; }

        /// <summary>
        /// Gets or Sets ANTRAGSTELLER_NR
        /// </summary>
        [DataMember(Name = "ANTRAGSTELLER_NR", EmitDefaultValue = false)]
        public string ANTRAGSTELLER_NR { get; set; }

        /// <summary>
        /// Gets or Sets KENNR
        /// </summary>
        [DataMember(Name = "KENNR", EmitDefaultValue = false)]
        public string KENNR { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AntragItems {\n");
            sb.Append("  ANTRAGNR: ").Append(ANTRAGNR).Append("\n");
            sb.Append("  ANTRAGSTELLER: ").Append(ANTRAGSTELLER).Append("\n");
            sb.Append("  ANTRAGSTELLER_NR: ").Append(ANTRAGSTELLER_NR).Append("\n");
            sb.Append("  KENNR: ").Append(KENNR).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AntragItems);
        }

        /// <summary>
        /// Returns true if AntragItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AntragItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AntragItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ANTRAGNR == input.ANTRAGNR ||
                    (this.ANTRAGNR != null &&
                    this.ANTRAGNR.Equals(input.ANTRAGNR))
                ) && 
                (
                    this.ANTRAGSTELLER == input.ANTRAGSTELLER ||
                    (this.ANTRAGSTELLER != null &&
                    this.ANTRAGSTELLER.Equals(input.ANTRAGSTELLER))
                ) && 
                (
                    this.ANTRAGSTELLER_NR == input.ANTRAGSTELLER_NR ||
                    (this.ANTRAGSTELLER_NR != null &&
                    this.ANTRAGSTELLER_NR.Equals(input.ANTRAGSTELLER_NR))
                ) && 
                (
                    this.KENNR == input.KENNR ||
                    (this.KENNR != null &&
                    this.KENNR.Equals(input.KENNR))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ANTRAGNR != null)
                    hashCode = hashCode * 59 + this.ANTRAGNR.GetHashCode();
                if (this.ANTRAGSTELLER != null)
                    hashCode = hashCode * 59 + this.ANTRAGSTELLER.GetHashCode();
                if (this.ANTRAGSTELLER_NR != null)
                    hashCode = hashCode * 59 + this.ANTRAGSTELLER_NR.GetHashCode();
                if (this.KENNR != null)
                    hashCode = hashCode * 59 + this.KENNR.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
