/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// AuflagenItems
    /// </summary>
    [DataContract(Name = "Auflagen_items")]
    public partial class AuflagenItems : IEquatable<AuflagenItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuflagenItems" /> class.
        /// </summary>
        /// <param name="aBSTAND">aBSTAND.</param>
        /// <param name="aNWENDBEST">aNWENDBEST.</param>
        /// <param name="aNWENDUNGSTECHNIK">aNWENDUNGSTECHNIK.</param>
        /// <param name="aUFLAGE">aUFLAGE.</param>
        /// <param name="aUFLAGENR">aUFLAGENR.</param>
        /// <param name="eBENE">eBENE.</param>
        /// <param name="kULTUR">kULTUR.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="rEDUABSTAND">rEDUABSTAND.</param>
        /// <param name="wEITEREBEDINGUNG">wEITEREBEDINGUNG.</param>
        public AuflagenItems(string aBSTAND = default(string), string aNWENDBEST = default(string), string aNWENDUNGSTECHNIK = default(string), string aUFLAGE = default(string), string aUFLAGENR = default(string), string eBENE = default(string), string kULTUR = default(string), string mROW = default(string), string rEDUABSTAND = default(string), string wEITEREBEDINGUNG = default(string))
        {
            this.ABSTAND = aBSTAND;
            this.ANWENDBEST = aNWENDBEST;
            this.ANWENDUNGSTECHNIK = aNWENDUNGSTECHNIK;
            this.AUFLAGE = aUFLAGE;
            this.AUFLAGENR = aUFLAGENR;
            this.EBENE = eBENE;
            this.KULTUR = kULTUR;
            this.M_ROW = mROW;
            this.REDU_ABSTAND = rEDUABSTAND;
            this.WEITERE_BEDINGUNG = wEITEREBEDINGUNG;
        }

        /// <summary>
        /// Gets or Sets ABSTAND
        /// </summary>
        [DataMember(Name = "ABSTAND", EmitDefaultValue = false)]
        public string ABSTAND { get; set; }

        /// <summary>
        /// Gets or Sets ANWENDBEST
        /// </summary>
        [DataMember(Name = "ANWENDBEST", EmitDefaultValue = false)]
        public string ANWENDBEST { get; set; }

        /// <summary>
        /// Gets or Sets ANWENDUNGSTECHNIK
        /// </summary>
        [DataMember(Name = "ANWENDUNGSTECHNIK", EmitDefaultValue = false)]
        public string ANWENDUNGSTECHNIK { get; set; }

        /// <summary>
        /// Gets or Sets AUFLAGE
        /// </summary>
        [DataMember(Name = "AUFLAGE", EmitDefaultValue = false)]
        public string AUFLAGE { get; set; }

        /// <summary>
        /// Gets or Sets AUFLAGENR
        /// </summary>
        [DataMember(Name = "AUFLAGENR", EmitDefaultValue = false)]
        public string AUFLAGENR { get; set; }

        /// <summary>
        /// Gets or Sets EBENE
        /// </summary>
        [DataMember(Name = "EBENE", EmitDefaultValue = false)]
        public string EBENE { get; set; }

        /// <summary>
        /// Gets or Sets KULTUR
        /// </summary>
        [DataMember(Name = "KULTUR", EmitDefaultValue = false)]
        public string KULTUR { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets REDU_ABSTAND
        /// </summary>
        [DataMember(Name = "REDU_ABSTAND", EmitDefaultValue = false)]
        public string REDU_ABSTAND { get; set; }

        /// <summary>
        /// Gets or Sets WEITERE_BEDINGUNG
        /// </summary>
        [DataMember(Name = "WEITERE_BEDINGUNG", EmitDefaultValue = false)]
        public string WEITERE_BEDINGUNG { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AuflagenItems {\n");
            sb.Append("  ABSTAND: ").Append(ABSTAND).Append("\n");
            sb.Append("  ANWENDBEST: ").Append(ANWENDBEST).Append("\n");
            sb.Append("  ANWENDUNGSTECHNIK: ").Append(ANWENDUNGSTECHNIK).Append("\n");
            sb.Append("  AUFLAGE: ").Append(AUFLAGE).Append("\n");
            sb.Append("  AUFLAGENR: ").Append(AUFLAGENR).Append("\n");
            sb.Append("  EBENE: ").Append(EBENE).Append("\n");
            sb.Append("  KULTUR: ").Append(KULTUR).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  REDU_ABSTAND: ").Append(REDU_ABSTAND).Append("\n");
            sb.Append("  WEITERE_BEDINGUNG: ").Append(WEITERE_BEDINGUNG).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuflagenItems);
        }

        /// <summary>
        /// Returns true if AuflagenItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AuflagenItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuflagenItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ABSTAND == input.ABSTAND ||
                    (this.ABSTAND != null &&
                    this.ABSTAND.Equals(input.ABSTAND))
                ) && 
                (
                    this.ANWENDBEST == input.ANWENDBEST ||
                    (this.ANWENDBEST != null &&
                    this.ANWENDBEST.Equals(input.ANWENDBEST))
                ) && 
                (
                    this.ANWENDUNGSTECHNIK == input.ANWENDUNGSTECHNIK ||
                    (this.ANWENDUNGSTECHNIK != null &&
                    this.ANWENDUNGSTECHNIK.Equals(input.ANWENDUNGSTECHNIK))
                ) && 
                (
                    this.AUFLAGE == input.AUFLAGE ||
                    (this.AUFLAGE != null &&
                    this.AUFLAGE.Equals(input.AUFLAGE))
                ) && 
                (
                    this.AUFLAGENR == input.AUFLAGENR ||
                    (this.AUFLAGENR != null &&
                    this.AUFLAGENR.Equals(input.AUFLAGENR))
                ) && 
                (
                    this.EBENE == input.EBENE ||
                    (this.EBENE != null &&
                    this.EBENE.Equals(input.EBENE))
                ) && 
                (
                    this.KULTUR == input.KULTUR ||
                    (this.KULTUR != null &&
                    this.KULTUR.Equals(input.KULTUR))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.REDU_ABSTAND == input.REDU_ABSTAND ||
                    (this.REDU_ABSTAND != null &&
                    this.REDU_ABSTAND.Equals(input.REDU_ABSTAND))
                ) && 
                (
                    this.WEITERE_BEDINGUNG == input.WEITERE_BEDINGUNG ||
                    (this.WEITERE_BEDINGUNG != null &&
                    this.WEITERE_BEDINGUNG.Equals(input.WEITERE_BEDINGUNG))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ABSTAND != null)
                    hashCode = hashCode * 59 + this.ABSTAND.GetHashCode();
                if (this.ANWENDBEST != null)
                    hashCode = hashCode * 59 + this.ANWENDBEST.GetHashCode();
                if (this.ANWENDUNGSTECHNIK != null)
                    hashCode = hashCode * 59 + this.ANWENDUNGSTECHNIK.GetHashCode();
                if (this.AUFLAGE != null)
                    hashCode = hashCode * 59 + this.AUFLAGE.GetHashCode();
                if (this.AUFLAGENR != null)
                    hashCode = hashCode * 59 + this.AUFLAGENR.GetHashCode();
                if (this.EBENE != null)
                    hashCode = hashCode * 59 + this.EBENE.GetHashCode();
                if (this.KULTUR != null)
                    hashCode = hashCode * 59 + this.KULTUR.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.REDU_ABSTAND != null)
                    hashCode = hashCode * 59 + this.REDU_ABSTAND.GetHashCode();
                if (this.WEITERE_BEDINGUNG != null)
                    hashCode = hashCode * 59 + this.WEITERE_BEDINGUNG.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
