/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// AuflageReduItems
    /// </summary>
    [DataContract(Name = "Auflage_Redu_items")]
    public partial class AuflageReduItems : IEquatable<AuflageReduItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuflageReduItems" /> class.
        /// </summary>
        /// <param name="aUFLAGENR">aUFLAGENR.</param>
        /// <param name="kATEGORIE">kATEGORIE.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="rEDUABSTAND">rEDUABSTAND.</param>
        public AuflageReduItems(string aUFLAGENR = default(string), string kATEGORIE = default(string), string mROW = default(string), string rEDUABSTAND = default(string))
        {
            this.AUFLAGENR = aUFLAGENR;
            this.KATEGORIE = kATEGORIE;
            this.M_ROW = mROW;
            this.REDU_ABSTAND = rEDUABSTAND;
        }

        /// <summary>
        /// Gets or Sets AUFLAGENR
        /// </summary>
        [DataMember(Name = "AUFLAGENR", EmitDefaultValue = false)]
        public string AUFLAGENR { get; set; }

        /// <summary>
        /// Gets or Sets KATEGORIE
        /// </summary>
        [DataMember(Name = "KATEGORIE", EmitDefaultValue = false)]
        public string KATEGORIE { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets REDU_ABSTAND
        /// </summary>
        [DataMember(Name = "REDU_ABSTAND", EmitDefaultValue = false)]
        public string REDU_ABSTAND { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AuflageReduItems {\n");
            sb.Append("  AUFLAGENR: ").Append(AUFLAGENR).Append("\n");
            sb.Append("  KATEGORIE: ").Append(KATEGORIE).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  REDU_ABSTAND: ").Append(REDU_ABSTAND).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuflageReduItems);
        }

        /// <summary>
        /// Returns true if AuflageReduItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AuflageReduItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuflageReduItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AUFLAGENR == input.AUFLAGENR ||
                    (this.AUFLAGENR != null &&
                    this.AUFLAGENR.Equals(input.AUFLAGENR))
                ) && 
                (
                    this.KATEGORIE == input.KATEGORIE ||
                    (this.KATEGORIE != null &&
                    this.KATEGORIE.Equals(input.KATEGORIE))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.REDU_ABSTAND == input.REDU_ABSTAND ||
                    (this.REDU_ABSTAND != null &&
                    this.REDU_ABSTAND.Equals(input.REDU_ABSTAND))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AUFLAGENR != null)
                    hashCode = hashCode * 59 + this.AUFLAGENR.GetHashCode();
                if (this.KATEGORIE != null)
                    hashCode = hashCode * 59 + this.KATEGORIE.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.REDU_ABSTAND != null)
                    hashCode = hashCode * 59 + this.REDU_ABSTAND.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
