/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// AwgAufwandItems
    /// </summary>
    [DataContract(Name = "Awg_Aufwand_items")]
    public partial class AwgAufwandItems : IEquatable<AwgAufwandItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AwgAufwandItems" /> class.
        /// </summary>
        /// <param name="aUFWANDBEDINGUNG">aUFWANDBEDINGUNG.</param>
        /// <param name="aWGID">aWGID.</param>
        /// <param name="mAUFWAND">mAUFWAND.</param>
        /// <param name="mAUFWANDEINHEIT">mAUFWANDEINHEIT.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="sORTIERNR">sORTIERNR.</param>
        /// <param name="wAUFWANDBIS">wAUFWANDBIS.</param>
        /// <param name="wAUFWANDEINHEIT">wAUFWANDEINHEIT.</param>
        /// <param name="wAUFWANDVON">wAUFWANDVON.</param>
        public AwgAufwandItems(string aUFWANDBEDINGUNG = default(string), string aWGID = default(string), string mAUFWAND = default(string), string mAUFWANDEINHEIT = default(string), string mROW = default(string), string sORTIERNR = default(string), string wAUFWANDBIS = default(string), string wAUFWANDEINHEIT = default(string), string wAUFWANDVON = default(string))
        {
            this.AUFWANDBEDINGUNG = aUFWANDBEDINGUNG;
            this.AWG_ID = aWGID;
            this.M_AUFWAND = mAUFWAND;
            this.M_AUFWAND_EINHEIT = mAUFWANDEINHEIT;
            this.M_ROW = mROW;
            this.SORTIER_NR = sORTIERNR;
            this.W_AUFWAND_BIS = wAUFWANDBIS;
            this.W_AUFWAND_EINHEIT = wAUFWANDEINHEIT;
            this.W_AUFWAND_VON = wAUFWANDVON;
        }

        /// <summary>
        /// Gets or Sets AUFWANDBEDINGUNG
        /// </summary>
        [DataMember(Name = "AUFWANDBEDINGUNG", EmitDefaultValue = false)]
        public string AUFWANDBEDINGUNG { get; set; }

        /// <summary>
        /// Gets or Sets AWG_ID
        /// </summary>
        [DataMember(Name = "AWG_ID", EmitDefaultValue = false)]
        public string AWG_ID { get; set; }

        /// <summary>
        /// Gets or Sets M_AUFWAND
        /// </summary>
        [DataMember(Name = "M_AUFWAND", EmitDefaultValue = false)]
        public string M_AUFWAND { get; set; }

        /// <summary>
        /// Gets or Sets M_AUFWAND_EINHEIT
        /// </summary>
        [DataMember(Name = "M_AUFWAND_EINHEIT", EmitDefaultValue = false)]
        public string M_AUFWAND_EINHEIT { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets SORTIER_NR
        /// </summary>
        [DataMember(Name = "SORTIER_NR", EmitDefaultValue = false)]
        public string SORTIER_NR { get; set; }

        /// <summary>
        /// Gets or Sets W_AUFWAND_BIS
        /// </summary>
        [DataMember(Name = "W_AUFWAND_BIS", EmitDefaultValue = false)]
        public string W_AUFWAND_BIS { get; set; }

        /// <summary>
        /// Gets or Sets W_AUFWAND_EINHEIT
        /// </summary>
        [DataMember(Name = "W_AUFWAND_EINHEIT", EmitDefaultValue = false)]
        public string W_AUFWAND_EINHEIT { get; set; }

        /// <summary>
        /// Gets or Sets W_AUFWAND_VON
        /// </summary>
        [DataMember(Name = "W_AUFWAND_VON", EmitDefaultValue = false)]
        public string W_AUFWAND_VON { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AwgAufwandItems {\n");
            sb.Append("  AUFWANDBEDINGUNG: ").Append(AUFWANDBEDINGUNG).Append("\n");
            sb.Append("  AWG_ID: ").Append(AWG_ID).Append("\n");
            sb.Append("  M_AUFWAND: ").Append(M_AUFWAND).Append("\n");
            sb.Append("  M_AUFWAND_EINHEIT: ").Append(M_AUFWAND_EINHEIT).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  SORTIER_NR: ").Append(SORTIER_NR).Append("\n");
            sb.Append("  W_AUFWAND_BIS: ").Append(W_AUFWAND_BIS).Append("\n");
            sb.Append("  W_AUFWAND_EINHEIT: ").Append(W_AUFWAND_EINHEIT).Append("\n");
            sb.Append("  W_AUFWAND_VON: ").Append(W_AUFWAND_VON).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AwgAufwandItems);
        }

        /// <summary>
        /// Returns true if AwgAufwandItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AwgAufwandItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AwgAufwandItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AUFWANDBEDINGUNG == input.AUFWANDBEDINGUNG ||
                    (this.AUFWANDBEDINGUNG != null &&
                    this.AUFWANDBEDINGUNG.Equals(input.AUFWANDBEDINGUNG))
                ) && 
                (
                    this.AWG_ID == input.AWG_ID ||
                    (this.AWG_ID != null &&
                    this.AWG_ID.Equals(input.AWG_ID))
                ) && 
                (
                    this.M_AUFWAND == input.M_AUFWAND ||
                    (this.M_AUFWAND != null &&
                    this.M_AUFWAND.Equals(input.M_AUFWAND))
                ) && 
                (
                    this.M_AUFWAND_EINHEIT == input.M_AUFWAND_EINHEIT ||
                    (this.M_AUFWAND_EINHEIT != null &&
                    this.M_AUFWAND_EINHEIT.Equals(input.M_AUFWAND_EINHEIT))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.SORTIER_NR == input.SORTIER_NR ||
                    (this.SORTIER_NR != null &&
                    this.SORTIER_NR.Equals(input.SORTIER_NR))
                ) && 
                (
                    this.W_AUFWAND_BIS == input.W_AUFWAND_BIS ||
                    (this.W_AUFWAND_BIS != null &&
                    this.W_AUFWAND_BIS.Equals(input.W_AUFWAND_BIS))
                ) && 
                (
                    this.W_AUFWAND_EINHEIT == input.W_AUFWAND_EINHEIT ||
                    (this.W_AUFWAND_EINHEIT != null &&
                    this.W_AUFWAND_EINHEIT.Equals(input.W_AUFWAND_EINHEIT))
                ) && 
                (
                    this.W_AUFWAND_VON == input.W_AUFWAND_VON ||
                    (this.W_AUFWAND_VON != null &&
                    this.W_AUFWAND_VON.Equals(input.W_AUFWAND_VON))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AUFWANDBEDINGUNG != null)
                    hashCode = hashCode * 59 + this.AUFWANDBEDINGUNG.GetHashCode();
                if (this.AWG_ID != null)
                    hashCode = hashCode * 59 + this.AWG_ID.GetHashCode();
                if (this.M_AUFWAND != null)
                    hashCode = hashCode * 59 + this.M_AUFWAND.GetHashCode();
                if (this.M_AUFWAND_EINHEIT != null)
                    hashCode = hashCode * 59 + this.M_AUFWAND_EINHEIT.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.SORTIER_NR != null)
                    hashCode = hashCode * 59 + this.SORTIER_NR.GetHashCode();
                if (this.W_AUFWAND_BIS != null)
                    hashCode = hashCode * 59 + this.W_AUFWAND_BIS.GetHashCode();
                if (this.W_AUFWAND_EINHEIT != null)
                    hashCode = hashCode * 59 + this.W_AUFWAND_EINHEIT.GetHashCode();
                if (this.W_AUFWAND_VON != null)
                    hashCode = hashCode * 59 + this.W_AUFWAND_VON.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
