/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// AwgBemItems
    /// </summary>
    [DataContract(Name = "Awg_Bem_items")]
    public partial class AwgBemItems : IEquatable<AwgBemItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AwgBemItems" /> class.
        /// </summary>
        /// <param name="aUFLAGEBEM">aUFLAGEBEM.</param>
        /// <param name="aUFLAGEBEREICH">aUFLAGEBEREICH.</param>
        /// <param name="aWGID">aWGID.</param>
        /// <param name="mROW">mROW.</param>
        public AwgBemItems(string aUFLAGEBEM = default(string), string aUFLAGEBEREICH = default(string), string aWGID = default(string), string mROW = default(string))
        {
            this.AUFLAGE_BEM = aUFLAGEBEM;
            this.AUFLAGE_BEREICH = aUFLAGEBEREICH;
            this.AWG_ID = aWGID;
            this.M_ROW = mROW;
        }

        /// <summary>
        /// Gets or Sets AUFLAGE_BEM
        /// </summary>
        [DataMember(Name = "AUFLAGE_BEM", EmitDefaultValue = false)]
        public string AUFLAGE_BEM { get; set; }

        /// <summary>
        /// Gets or Sets AUFLAGE_BEREICH
        /// </summary>
        [DataMember(Name = "AUFLAGE_BEREICH", EmitDefaultValue = false)]
        public string AUFLAGE_BEREICH { get; set; }

        /// <summary>
        /// Gets or Sets AWG_ID
        /// </summary>
        [DataMember(Name = "AWG_ID", EmitDefaultValue = false)]
        public string AWG_ID { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AwgBemItems {\n");
            sb.Append("  AUFLAGE_BEM: ").Append(AUFLAGE_BEM).Append("\n");
            sb.Append("  AUFLAGE_BEREICH: ").Append(AUFLAGE_BEREICH).Append("\n");
            sb.Append("  AWG_ID: ").Append(AWG_ID).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AwgBemItems);
        }

        /// <summary>
        /// Returns true if AwgBemItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AwgBemItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AwgBemItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AUFLAGE_BEM == input.AUFLAGE_BEM ||
                    (this.AUFLAGE_BEM != null &&
                    this.AUFLAGE_BEM.Equals(input.AUFLAGE_BEM))
                ) && 
                (
                    this.AUFLAGE_BEREICH == input.AUFLAGE_BEREICH ||
                    (this.AUFLAGE_BEREICH != null &&
                    this.AUFLAGE_BEREICH.Equals(input.AUFLAGE_BEREICH))
                ) && 
                (
                    this.AWG_ID == input.AWG_ID ||
                    (this.AWG_ID != null &&
                    this.AWG_ID.Equals(input.AWG_ID))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AUFLAGE_BEM != null)
                    hashCode = hashCode * 59 + this.AUFLAGE_BEM.GetHashCode();
                if (this.AUFLAGE_BEREICH != null)
                    hashCode = hashCode * 59 + this.AUFLAGE_BEREICH.GetHashCode();
                if (this.AWG_ID != null)
                    hashCode = hashCode * 59 + this.AWG_ID.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
