/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// AwgItems
    /// </summary>
    [DataContract(Name = "Awg_items")]
    public partial class AwgItems : IEquatable<AwgItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AwgItems" /> class.
        /// </summary>
        /// <param name="aNTRAGNR">aNTRAGNR.</param>
        /// <param name="aNWENDUNGENANZJEBEFALL">aNWENDUNGENANZJEBEFALL.</param>
        /// <param name="aNWENDUNGENMAXJEKULTUR">aNWENDUNGENMAXJEKULTUR.</param>
        /// <param name="aNWENDUNGENMAXJEVEGETATION">aNWENDUNGENMAXJEVEGETATION.</param>
        /// <param name="aNWENDUNGSBEREICH">aNWENDUNGSBEREICH.</param>
        /// <param name="aNWENDUNGSTECHNIK">aNWENDUNGSTECHNIK.</param>
        /// <param name="aWGNR">aWGNR.</param>
        /// <param name="aWGID">aWGID.</param>
        /// <param name="aWABSTANDBIS">aWABSTANDBIS.</param>
        /// <param name="aWABSTANDEINHEIT">aWABSTANDEINHEIT.</param>
        /// <param name="aWABSTANDVON">aWABSTANDVON.</param>
        /// <param name="eINSATZGEBIET">eINSATZGEBIET.</param>
        /// <param name="gENEHMIGUNG">gENEHMIGUNG.</param>
        /// <param name="hUK">hUK.</param>
        /// <param name="kENNR">kENNR.</param>
        /// <param name="kULTURERL">kULTURERL.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="sCHADORGERL">sCHADORGERL.</param>
        /// <param name="sTADIUMKULTURBEM">sTADIUMKULTURBEM.</param>
        /// <param name="sTADIUMKULTURBIS">sTADIUMKULTURBIS.</param>
        /// <param name="sTADIUMKULTURKODELISTE">sTADIUMKULTURKODELISTE.</param>
        /// <param name="sTADIUMKULTURVON">sTADIUMKULTURVON.</param>
        /// <param name="sTADIUMSCHADORGBEM">sTADIUMSCHADORGBEM.</param>
        /// <param name="sTADIUMSCHADORGBIS">sTADIUMSCHADORGBIS.</param>
        /// <param name="sTADIUMSCHADORGKODELISTE">sTADIUMSCHADORGKODELISTE.</param>
        /// <param name="sTADIUMSCHADORGVON">sTADIUMSCHADORGVON.</param>
        /// <param name="wIRKUNGSBEREICH">wIRKUNGSBEREICH.</param>
        public AwgItems(string aNTRAGNR = default(string), string aNWENDUNGENANZJEBEFALL = default(string), string aNWENDUNGENMAXJEKULTUR = default(string), string aNWENDUNGENMAXJEVEGETATION = default(string), string aNWENDUNGSBEREICH = default(string), string aNWENDUNGSTECHNIK = default(string), string aWGNR = default(string), string aWGID = default(string), string aWABSTANDBIS = default(string), string aWABSTANDEINHEIT = default(string), string aWABSTANDVON = default(string), string eINSATZGEBIET = default(string), string gENEHMIGUNG = default(string), string hUK = default(string), string kENNR = default(string), string kULTURERL = default(string), string mROW = default(string), string sCHADORGERL = default(string), string sTADIUMKULTURBEM = default(string), string sTADIUMKULTURBIS = default(string), string sTADIUMKULTURKODELISTE = default(string), string sTADIUMKULTURVON = default(string), string sTADIUMSCHADORGBEM = default(string), string sTADIUMSCHADORGBIS = default(string), string sTADIUMSCHADORGKODELISTE = default(string), string sTADIUMSCHADORGVON = default(string), string wIRKUNGSBEREICH = default(string))
        {
            this.ANTRAGNR = aNTRAGNR;
            this.ANWENDUNGEN_ANZ_JE_BEFALL = aNWENDUNGENANZJEBEFALL;
            this.ANWENDUNGEN_MAX_JE_KULTUR = aNWENDUNGENMAXJEKULTUR;
            this.ANWENDUNGEN_MAX_JE_VEGETATION = aNWENDUNGENMAXJEVEGETATION;
            this.ANWENDUNGSBEREICH = aNWENDUNGSBEREICH;
            this.ANWENDUNGSTECHNIK = aNWENDUNGSTECHNIK;
            this.AWGNR = aWGNR;
            this.AWG_ID = aWGID;
            this.AW_ABSTAND_BIS = aWABSTANDBIS;
            this.AW_ABSTAND_EINHEIT = aWABSTANDEINHEIT;
            this.AW_ABSTAND_VON = aWABSTANDVON;
            this.EINSATZGEBIET = eINSATZGEBIET;
            this.GENEHMIGUNG = gENEHMIGUNG;
            this.HUK = hUK;
            this.KENNR = kENNR;
            this.KULTUR_ERL = kULTURERL;
            this.M_ROW = mROW;
            this.SCHADORG_ERL = sCHADORGERL;
            this.STADIUM_KULTUR_BEM = sTADIUMKULTURBEM;
            this.STADIUM_KULTUR_BIS = sTADIUMKULTURBIS;
            this.STADIUM_KULTUR_KODELISTE = sTADIUMKULTURKODELISTE;
            this.STADIUM_KULTUR_VON = sTADIUMKULTURVON;
            this.STADIUM_SCHADORG_BEM = sTADIUMSCHADORGBEM;
            this.STADIUM_SCHADORG_BIS = sTADIUMSCHADORGBIS;
            this.STADIUM_SCHADORG_KODELISTE = sTADIUMSCHADORGKODELISTE;
            this.STADIUM_SCHADORG_VON = sTADIUMSCHADORGVON;
            this.WIRKUNGSBEREICH = wIRKUNGSBEREICH;
        }

        /// <summary>
        /// Gets or Sets ANTRAGNR
        /// </summary>
        [DataMember(Name = "ANTRAGNR", EmitDefaultValue = false)]
        public string ANTRAGNR { get; set; }

        /// <summary>
        /// Gets or Sets ANWENDUNGEN_ANZ_JE_BEFALL
        /// </summary>
        [DataMember(Name = "ANWENDUNGEN_ANZ_JE_BEFALL", EmitDefaultValue = false)]
        public string ANWENDUNGEN_ANZ_JE_BEFALL { get; set; }

        /// <summary>
        /// Gets or Sets ANWENDUNGEN_MAX_JE_KULTUR
        /// </summary>
        [DataMember(Name = "ANWENDUNGEN_MAX_JE_KULTUR", EmitDefaultValue = false)]
        public string ANWENDUNGEN_MAX_JE_KULTUR { get; set; }

        /// <summary>
        /// Gets or Sets ANWENDUNGEN_MAX_JE_VEGETATION
        /// </summary>
        [DataMember(Name = "ANWENDUNGEN_MAX_JE_VEGETATION", EmitDefaultValue = false)]
        public string ANWENDUNGEN_MAX_JE_VEGETATION { get; set; }

        /// <summary>
        /// Gets or Sets ANWENDUNGSBEREICH
        /// </summary>
        [DataMember(Name = "ANWENDUNGSBEREICH", EmitDefaultValue = false)]
        public string ANWENDUNGSBEREICH { get; set; }

        /// <summary>
        /// Gets or Sets ANWENDUNGSTECHNIK
        /// </summary>
        [DataMember(Name = "ANWENDUNGSTECHNIK", EmitDefaultValue = false)]
        public string ANWENDUNGSTECHNIK { get; set; }

        /// <summary>
        /// Gets or Sets AWGNR
        /// </summary>
        [DataMember(Name = "AWGNR", EmitDefaultValue = false)]
        public string AWGNR { get; set; }

        /// <summary>
        /// Gets or Sets AWG_ID
        /// </summary>
        [DataMember(Name = "AWG_ID", EmitDefaultValue = false)]
        public string AWG_ID { get; set; }

        /// <summary>
        /// Gets or Sets AW_ABSTAND_BIS
        /// </summary>
        [DataMember(Name = "AW_ABSTAND_BIS", EmitDefaultValue = false)]
        public string AW_ABSTAND_BIS { get; set; }

        /// <summary>
        /// Gets or Sets AW_ABSTAND_EINHEIT
        /// </summary>
        [DataMember(Name = "AW_ABSTAND_EINHEIT", EmitDefaultValue = false)]
        public string AW_ABSTAND_EINHEIT { get; set; }

        /// <summary>
        /// Gets or Sets AW_ABSTAND_VON
        /// </summary>
        [DataMember(Name = "AW_ABSTAND_VON", EmitDefaultValue = false)]
        public string AW_ABSTAND_VON { get; set; }

        /// <summary>
        /// Gets or Sets EINSATZGEBIET
        /// </summary>
        [DataMember(Name = "EINSATZGEBIET", EmitDefaultValue = false)]
        public string EINSATZGEBIET { get; set; }

        /// <summary>
        /// Gets or Sets GENEHMIGUNG
        /// </summary>
        [DataMember(Name = "GENEHMIGUNG", EmitDefaultValue = false)]
        public string GENEHMIGUNG { get; set; }

        /// <summary>
        /// Gets or Sets HUK
        /// </summary>
        [DataMember(Name = "HUK", EmitDefaultValue = false)]
        public string HUK { get; set; }

        /// <summary>
        /// Gets or Sets KENNR
        /// </summary>
        [DataMember(Name = "KENNR", EmitDefaultValue = false)]
        public string KENNR { get; set; }

        /// <summary>
        /// Gets or Sets KULTUR_ERL
        /// </summary>
        [DataMember(Name = "KULTUR_ERL", EmitDefaultValue = false)]
        public string KULTUR_ERL { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets SCHADORG_ERL
        /// </summary>
        [DataMember(Name = "SCHADORG_ERL", EmitDefaultValue = false)]
        public string SCHADORG_ERL { get; set; }

        /// <summary>
        /// Gets or Sets STADIUM_KULTUR_BEM
        /// </summary>
        [DataMember(Name = "STADIUM_KULTUR_BEM", EmitDefaultValue = false)]
        public string STADIUM_KULTUR_BEM { get; set; }

        /// <summary>
        /// Gets or Sets STADIUM_KULTUR_BIS
        /// </summary>
        [DataMember(Name = "STADIUM_KULTUR_BIS", EmitDefaultValue = false)]
        public string STADIUM_KULTUR_BIS { get; set; }

        /// <summary>
        /// Gets or Sets STADIUM_KULTUR_KODELISTE
        /// </summary>
        [DataMember(Name = "STADIUM_KULTUR_KODELISTE", EmitDefaultValue = false)]
        public string STADIUM_KULTUR_KODELISTE { get; set; }

        /// <summary>
        /// Gets or Sets STADIUM_KULTUR_VON
        /// </summary>
        [DataMember(Name = "STADIUM_KULTUR_VON", EmitDefaultValue = false)]
        public string STADIUM_KULTUR_VON { get; set; }

        /// <summary>
        /// Gets or Sets STADIUM_SCHADORG_BEM
        /// </summary>
        [DataMember(Name = "STADIUM_SCHADORG_BEM", EmitDefaultValue = false)]
        public string STADIUM_SCHADORG_BEM { get; set; }

        /// <summary>
        /// Gets or Sets STADIUM_SCHADORG_BIS
        /// </summary>
        [DataMember(Name = "STADIUM_SCHADORG_BIS", EmitDefaultValue = false)]
        public string STADIUM_SCHADORG_BIS { get; set; }

        /// <summary>
        /// Gets or Sets STADIUM_SCHADORG_KODELISTE
        /// </summary>
        [DataMember(Name = "STADIUM_SCHADORG_KODELISTE", EmitDefaultValue = false)]
        public string STADIUM_SCHADORG_KODELISTE { get; set; }

        /// <summary>
        /// Gets or Sets STADIUM_SCHADORG_VON
        /// </summary>
        [DataMember(Name = "STADIUM_SCHADORG_VON", EmitDefaultValue = false)]
        public string STADIUM_SCHADORG_VON { get; set; }

        /// <summary>
        /// Gets or Sets WIRKUNGSBEREICH
        /// </summary>
        [DataMember(Name = "WIRKUNGSBEREICH", EmitDefaultValue = false)]
        public string WIRKUNGSBEREICH { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AwgItems {\n");
            sb.Append("  ANTRAGNR: ").Append(ANTRAGNR).Append("\n");
            sb.Append("  ANWENDUNGEN_ANZ_JE_BEFALL: ").Append(ANWENDUNGEN_ANZ_JE_BEFALL).Append("\n");
            sb.Append("  ANWENDUNGEN_MAX_JE_KULTUR: ").Append(ANWENDUNGEN_MAX_JE_KULTUR).Append("\n");
            sb.Append("  ANWENDUNGEN_MAX_JE_VEGETATION: ").Append(ANWENDUNGEN_MAX_JE_VEGETATION).Append("\n");
            sb.Append("  ANWENDUNGSBEREICH: ").Append(ANWENDUNGSBEREICH).Append("\n");
            sb.Append("  ANWENDUNGSTECHNIK: ").Append(ANWENDUNGSTECHNIK).Append("\n");
            sb.Append("  AWGNR: ").Append(AWGNR).Append("\n");
            sb.Append("  AWG_ID: ").Append(AWG_ID).Append("\n");
            sb.Append("  AW_ABSTAND_BIS: ").Append(AW_ABSTAND_BIS).Append("\n");
            sb.Append("  AW_ABSTAND_EINHEIT: ").Append(AW_ABSTAND_EINHEIT).Append("\n");
            sb.Append("  AW_ABSTAND_VON: ").Append(AW_ABSTAND_VON).Append("\n");
            sb.Append("  EINSATZGEBIET: ").Append(EINSATZGEBIET).Append("\n");
            sb.Append("  GENEHMIGUNG: ").Append(GENEHMIGUNG).Append("\n");
            sb.Append("  HUK: ").Append(HUK).Append("\n");
            sb.Append("  KENNR: ").Append(KENNR).Append("\n");
            sb.Append("  KULTUR_ERL: ").Append(KULTUR_ERL).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  SCHADORG_ERL: ").Append(SCHADORG_ERL).Append("\n");
            sb.Append("  STADIUM_KULTUR_BEM: ").Append(STADIUM_KULTUR_BEM).Append("\n");
            sb.Append("  STADIUM_KULTUR_BIS: ").Append(STADIUM_KULTUR_BIS).Append("\n");
            sb.Append("  STADIUM_KULTUR_KODELISTE: ").Append(STADIUM_KULTUR_KODELISTE).Append("\n");
            sb.Append("  STADIUM_KULTUR_VON: ").Append(STADIUM_KULTUR_VON).Append("\n");
            sb.Append("  STADIUM_SCHADORG_BEM: ").Append(STADIUM_SCHADORG_BEM).Append("\n");
            sb.Append("  STADIUM_SCHADORG_BIS: ").Append(STADIUM_SCHADORG_BIS).Append("\n");
            sb.Append("  STADIUM_SCHADORG_KODELISTE: ").Append(STADIUM_SCHADORG_KODELISTE).Append("\n");
            sb.Append("  STADIUM_SCHADORG_VON: ").Append(STADIUM_SCHADORG_VON).Append("\n");
            sb.Append("  WIRKUNGSBEREICH: ").Append(WIRKUNGSBEREICH).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AwgItems);
        }

        /// <summary>
        /// Returns true if AwgItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AwgItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AwgItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ANTRAGNR == input.ANTRAGNR ||
                    (this.ANTRAGNR != null &&
                    this.ANTRAGNR.Equals(input.ANTRAGNR))
                ) && 
                (
                    this.ANWENDUNGEN_ANZ_JE_BEFALL == input.ANWENDUNGEN_ANZ_JE_BEFALL ||
                    (this.ANWENDUNGEN_ANZ_JE_BEFALL != null &&
                    this.ANWENDUNGEN_ANZ_JE_BEFALL.Equals(input.ANWENDUNGEN_ANZ_JE_BEFALL))
                ) && 
                (
                    this.ANWENDUNGEN_MAX_JE_KULTUR == input.ANWENDUNGEN_MAX_JE_KULTUR ||
                    (this.ANWENDUNGEN_MAX_JE_KULTUR != null &&
                    this.ANWENDUNGEN_MAX_JE_KULTUR.Equals(input.ANWENDUNGEN_MAX_JE_KULTUR))
                ) && 
                (
                    this.ANWENDUNGEN_MAX_JE_VEGETATION == input.ANWENDUNGEN_MAX_JE_VEGETATION ||
                    (this.ANWENDUNGEN_MAX_JE_VEGETATION != null &&
                    this.ANWENDUNGEN_MAX_JE_VEGETATION.Equals(input.ANWENDUNGEN_MAX_JE_VEGETATION))
                ) && 
                (
                    this.ANWENDUNGSBEREICH == input.ANWENDUNGSBEREICH ||
                    (this.ANWENDUNGSBEREICH != null &&
                    this.ANWENDUNGSBEREICH.Equals(input.ANWENDUNGSBEREICH))
                ) && 
                (
                    this.ANWENDUNGSTECHNIK == input.ANWENDUNGSTECHNIK ||
                    (this.ANWENDUNGSTECHNIK != null &&
                    this.ANWENDUNGSTECHNIK.Equals(input.ANWENDUNGSTECHNIK))
                ) && 
                (
                    this.AWGNR == input.AWGNR ||
                    (this.AWGNR != null &&
                    this.AWGNR.Equals(input.AWGNR))
                ) && 
                (
                    this.AWG_ID == input.AWG_ID ||
                    (this.AWG_ID != null &&
                    this.AWG_ID.Equals(input.AWG_ID))
                ) && 
                (
                    this.AW_ABSTAND_BIS == input.AW_ABSTAND_BIS ||
                    (this.AW_ABSTAND_BIS != null &&
                    this.AW_ABSTAND_BIS.Equals(input.AW_ABSTAND_BIS))
                ) && 
                (
                    this.AW_ABSTAND_EINHEIT == input.AW_ABSTAND_EINHEIT ||
                    (this.AW_ABSTAND_EINHEIT != null &&
                    this.AW_ABSTAND_EINHEIT.Equals(input.AW_ABSTAND_EINHEIT))
                ) && 
                (
                    this.AW_ABSTAND_VON == input.AW_ABSTAND_VON ||
                    (this.AW_ABSTAND_VON != null &&
                    this.AW_ABSTAND_VON.Equals(input.AW_ABSTAND_VON))
                ) && 
                (
                    this.EINSATZGEBIET == input.EINSATZGEBIET ||
                    (this.EINSATZGEBIET != null &&
                    this.EINSATZGEBIET.Equals(input.EINSATZGEBIET))
                ) && 
                (
                    this.GENEHMIGUNG == input.GENEHMIGUNG ||
                    (this.GENEHMIGUNG != null &&
                    this.GENEHMIGUNG.Equals(input.GENEHMIGUNG))
                ) && 
                (
                    this.HUK == input.HUK ||
                    (this.HUK != null &&
                    this.HUK.Equals(input.HUK))
                ) && 
                (
                    this.KENNR == input.KENNR ||
                    (this.KENNR != null &&
                    this.KENNR.Equals(input.KENNR))
                ) && 
                (
                    this.KULTUR_ERL == input.KULTUR_ERL ||
                    (this.KULTUR_ERL != null &&
                    this.KULTUR_ERL.Equals(input.KULTUR_ERL))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.SCHADORG_ERL == input.SCHADORG_ERL ||
                    (this.SCHADORG_ERL != null &&
                    this.SCHADORG_ERL.Equals(input.SCHADORG_ERL))
                ) && 
                (
                    this.STADIUM_KULTUR_BEM == input.STADIUM_KULTUR_BEM ||
                    (this.STADIUM_KULTUR_BEM != null &&
                    this.STADIUM_KULTUR_BEM.Equals(input.STADIUM_KULTUR_BEM))
                ) && 
                (
                    this.STADIUM_KULTUR_BIS == input.STADIUM_KULTUR_BIS ||
                    (this.STADIUM_KULTUR_BIS != null &&
                    this.STADIUM_KULTUR_BIS.Equals(input.STADIUM_KULTUR_BIS))
                ) && 
                (
                    this.STADIUM_KULTUR_KODELISTE == input.STADIUM_KULTUR_KODELISTE ||
                    (this.STADIUM_KULTUR_KODELISTE != null &&
                    this.STADIUM_KULTUR_KODELISTE.Equals(input.STADIUM_KULTUR_KODELISTE))
                ) && 
                (
                    this.STADIUM_KULTUR_VON == input.STADIUM_KULTUR_VON ||
                    (this.STADIUM_KULTUR_VON != null &&
                    this.STADIUM_KULTUR_VON.Equals(input.STADIUM_KULTUR_VON))
                ) && 
                (
                    this.STADIUM_SCHADORG_BEM == input.STADIUM_SCHADORG_BEM ||
                    (this.STADIUM_SCHADORG_BEM != null &&
                    this.STADIUM_SCHADORG_BEM.Equals(input.STADIUM_SCHADORG_BEM))
                ) && 
                (
                    this.STADIUM_SCHADORG_BIS == input.STADIUM_SCHADORG_BIS ||
                    (this.STADIUM_SCHADORG_BIS != null &&
                    this.STADIUM_SCHADORG_BIS.Equals(input.STADIUM_SCHADORG_BIS))
                ) && 
                (
                    this.STADIUM_SCHADORG_KODELISTE == input.STADIUM_SCHADORG_KODELISTE ||
                    (this.STADIUM_SCHADORG_KODELISTE != null &&
                    this.STADIUM_SCHADORG_KODELISTE.Equals(input.STADIUM_SCHADORG_KODELISTE))
                ) && 
                (
                    this.STADIUM_SCHADORG_VON == input.STADIUM_SCHADORG_VON ||
                    (this.STADIUM_SCHADORG_VON != null &&
                    this.STADIUM_SCHADORG_VON.Equals(input.STADIUM_SCHADORG_VON))
                ) && 
                (
                    this.WIRKUNGSBEREICH == input.WIRKUNGSBEREICH ||
                    (this.WIRKUNGSBEREICH != null &&
                    this.WIRKUNGSBEREICH.Equals(input.WIRKUNGSBEREICH))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ANTRAGNR != null)
                    hashCode = hashCode * 59 + this.ANTRAGNR.GetHashCode();
                if (this.ANWENDUNGEN_ANZ_JE_BEFALL != null)
                    hashCode = hashCode * 59 + this.ANWENDUNGEN_ANZ_JE_BEFALL.GetHashCode();
                if (this.ANWENDUNGEN_MAX_JE_KULTUR != null)
                    hashCode = hashCode * 59 + this.ANWENDUNGEN_MAX_JE_KULTUR.GetHashCode();
                if (this.ANWENDUNGEN_MAX_JE_VEGETATION != null)
                    hashCode = hashCode * 59 + this.ANWENDUNGEN_MAX_JE_VEGETATION.GetHashCode();
                if (this.ANWENDUNGSBEREICH != null)
                    hashCode = hashCode * 59 + this.ANWENDUNGSBEREICH.GetHashCode();
                if (this.ANWENDUNGSTECHNIK != null)
                    hashCode = hashCode * 59 + this.ANWENDUNGSTECHNIK.GetHashCode();
                if (this.AWGNR != null)
                    hashCode = hashCode * 59 + this.AWGNR.GetHashCode();
                if (this.AWG_ID != null)
                    hashCode = hashCode * 59 + this.AWG_ID.GetHashCode();
                if (this.AW_ABSTAND_BIS != null)
                    hashCode = hashCode * 59 + this.AW_ABSTAND_BIS.GetHashCode();
                if (this.AW_ABSTAND_EINHEIT != null)
                    hashCode = hashCode * 59 + this.AW_ABSTAND_EINHEIT.GetHashCode();
                if (this.AW_ABSTAND_VON != null)
                    hashCode = hashCode * 59 + this.AW_ABSTAND_VON.GetHashCode();
                if (this.EINSATZGEBIET != null)
                    hashCode = hashCode * 59 + this.EINSATZGEBIET.GetHashCode();
                if (this.GENEHMIGUNG != null)
                    hashCode = hashCode * 59 + this.GENEHMIGUNG.GetHashCode();
                if (this.HUK != null)
                    hashCode = hashCode * 59 + this.HUK.GetHashCode();
                if (this.KENNR != null)
                    hashCode = hashCode * 59 + this.KENNR.GetHashCode();
                if (this.KULTUR_ERL != null)
                    hashCode = hashCode * 59 + this.KULTUR_ERL.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.SCHADORG_ERL != null)
                    hashCode = hashCode * 59 + this.SCHADORG_ERL.GetHashCode();
                if (this.STADIUM_KULTUR_BEM != null)
                    hashCode = hashCode * 59 + this.STADIUM_KULTUR_BEM.GetHashCode();
                if (this.STADIUM_KULTUR_BIS != null)
                    hashCode = hashCode * 59 + this.STADIUM_KULTUR_BIS.GetHashCode();
                if (this.STADIUM_KULTUR_KODELISTE != null)
                    hashCode = hashCode * 59 + this.STADIUM_KULTUR_KODELISTE.GetHashCode();
                if (this.STADIUM_KULTUR_VON != null)
                    hashCode = hashCode * 59 + this.STADIUM_KULTUR_VON.GetHashCode();
                if (this.STADIUM_SCHADORG_BEM != null)
                    hashCode = hashCode * 59 + this.STADIUM_SCHADORG_BEM.GetHashCode();
                if (this.STADIUM_SCHADORG_BIS != null)
                    hashCode = hashCode * 59 + this.STADIUM_SCHADORG_BIS.GetHashCode();
                if (this.STADIUM_SCHADORG_KODELISTE != null)
                    hashCode = hashCode * 59 + this.STADIUM_SCHADORG_KODELISTE.GetHashCode();
                if (this.STADIUM_SCHADORG_VON != null)
                    hashCode = hashCode * 59 + this.STADIUM_SCHADORG_VON.GetHashCode();
                if (this.WIRKUNGSBEREICH != null)
                    hashCode = hashCode * 59 + this.WIRKUNGSBEREICH.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
