/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// AwgPartnerItems
    /// </summary>
    [DataContract(Name = "Awg_Partner_items")]
    public partial class AwgPartnerItems : IEquatable<AwgPartnerItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AwgPartnerItems" /> class.
        /// </summary>
        /// <param name="aWGID">aWGID.</param>
        /// <param name="mISCHUNGART">mISCHUNGART.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="pARTNERKENNR">pARTNERKENNR.</param>
        public AwgPartnerItems(string aWGID = default(string), string mISCHUNGART = default(string), string mROW = default(string), string pARTNERKENNR = default(string))
        {
            this.AWG_ID = aWGID;
            this.MISCHUNG_ART = mISCHUNGART;
            this.M_ROW = mROW;
            this.PARTNER_KENNR = pARTNERKENNR;
        }

        /// <summary>
        /// Gets or Sets AWG_ID
        /// </summary>
        [DataMember(Name = "AWG_ID", EmitDefaultValue = false)]
        public string AWG_ID { get; set; }

        /// <summary>
        /// Gets or Sets MISCHUNG_ART
        /// </summary>
        [DataMember(Name = "MISCHUNG_ART", EmitDefaultValue = false)]
        public string MISCHUNG_ART { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets PARTNER_KENNR
        /// </summary>
        [DataMember(Name = "PARTNER_KENNR", EmitDefaultValue = false)]
        public string PARTNER_KENNR { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AwgPartnerItems {\n");
            sb.Append("  AWG_ID: ").Append(AWG_ID).Append("\n");
            sb.Append("  MISCHUNG_ART: ").Append(MISCHUNG_ART).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  PARTNER_KENNR: ").Append(PARTNER_KENNR).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AwgPartnerItems);
        }

        /// <summary>
        /// Returns true if AwgPartnerItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AwgPartnerItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AwgPartnerItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AWG_ID == input.AWG_ID ||
                    (this.AWG_ID != null &&
                    this.AWG_ID.Equals(input.AWG_ID))
                ) && 
                (
                    this.MISCHUNG_ART == input.MISCHUNG_ART ||
                    (this.MISCHUNG_ART != null &&
                    this.MISCHUNG_ART.Equals(input.MISCHUNG_ART))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.PARTNER_KENNR == input.PARTNER_KENNR ||
                    (this.PARTNER_KENNR != null &&
                    this.PARTNER_KENNR.Equals(input.PARTNER_KENNR))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AWG_ID != null)
                    hashCode = hashCode * 59 + this.AWG_ID.GetHashCode();
                if (this.MISCHUNG_ART != null)
                    hashCode = hashCode * 59 + this.MISCHUNG_ART.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.PARTNER_KENNR != null)
                    hashCode = hashCode * 59 + this.PARTNER_KENNR.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
