/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// AwgSchadorgItems
    /// </summary>
    [DataContract(Name = "Awg_Schadorg_items")]
    public partial class AwgSchadorgItems : IEquatable<AwgSchadorgItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AwgSchadorgItems" /> class.
        /// </summary>
        /// <param name="aUSGENOMMEN">aUSGENOMMEN.</param>
        /// <param name="aWGID">aWGID.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="sCHADORG">sCHADORG.</param>
        /// <param name="sORTIERNR">sORTIERNR.</param>
        public AwgSchadorgItems(string aUSGENOMMEN = default(string), string aWGID = default(string), string mROW = default(string), string sCHADORG = default(string), string sORTIERNR = default(string))
        {
            this.AUSGENOMMEN = aUSGENOMMEN;
            this.AWG_ID = aWGID;
            this.M_ROW = mROW;
            this.SCHADORG = sCHADORG;
            this.SORTIER_NR = sORTIERNR;
        }

        /// <summary>
        /// Gets or Sets AUSGENOMMEN
        /// </summary>
        [DataMember(Name = "AUSGENOMMEN", EmitDefaultValue = false)]
        public string AUSGENOMMEN { get; set; }

        /// <summary>
        /// Gets or Sets AWG_ID
        /// </summary>
        [DataMember(Name = "AWG_ID", EmitDefaultValue = false)]
        public string AWG_ID { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets SCHADORG
        /// </summary>
        [DataMember(Name = "SCHADORG", EmitDefaultValue = false)]
        public string SCHADORG { get; set; }

        /// <summary>
        /// Gets or Sets SORTIER_NR
        /// </summary>
        [DataMember(Name = "SORTIER_NR", EmitDefaultValue = false)]
        public string SORTIER_NR { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AwgSchadorgItems {\n");
            sb.Append("  AUSGENOMMEN: ").Append(AUSGENOMMEN).Append("\n");
            sb.Append("  AWG_ID: ").Append(AWG_ID).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  SCHADORG: ").Append(SCHADORG).Append("\n");
            sb.Append("  SORTIER_NR: ").Append(SORTIER_NR).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AwgSchadorgItems);
        }

        /// <summary>
        /// Returns true if AwgSchadorgItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AwgSchadorgItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AwgSchadorgItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AUSGENOMMEN == input.AUSGENOMMEN ||
                    (this.AUSGENOMMEN != null &&
                    this.AUSGENOMMEN.Equals(input.AUSGENOMMEN))
                ) && 
                (
                    this.AWG_ID == input.AWG_ID ||
                    (this.AWG_ID != null &&
                    this.AWG_ID.Equals(input.AWG_ID))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.SCHADORG == input.SCHADORG ||
                    (this.SCHADORG != null &&
                    this.SCHADORG.Equals(input.SCHADORG))
                ) && 
                (
                    this.SORTIER_NR == input.SORTIER_NR ||
                    (this.SORTIER_NR != null &&
                    this.SORTIER_NR.Equals(input.SORTIER_NR))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AUSGENOMMEN != null)
                    hashCode = hashCode * 59 + this.AUSGENOMMEN.GetHashCode();
                if (this.AWG_ID != null)
                    hashCode = hashCode * 59 + this.AWG_ID.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.SCHADORG != null)
                    hashCode = hashCode * 59 + this.SCHADORG.GetHashCode();
                if (this.SORTIER_NR != null)
                    hashCode = hashCode * 59 + this.SORTIER_NR.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
