/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// AwgWartezeitItems
    /// </summary>
    [DataContract(Name = "Awg_Wartezeit_items")]
    public partial class AwgWartezeitItems : IEquatable<AwgWartezeitItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AwgWartezeitItems" /> class.
        /// </summary>
        /// <param name="aNWENDUNGSBEREICH">aNWENDUNGSBEREICH.</param>
        /// <param name="aWGID">aWGID.</param>
        /// <param name="aWGWARTEZEITNR">aWGWARTEZEITNR.</param>
        /// <param name="eRLAEUTERUNG">eRLAEUTERUNG.</param>
        /// <param name="gESETZTWARTEZEIT">gESETZTWARTEZEIT.</param>
        /// <param name="gESETZTWARTEZEITBEM">gESETZTWARTEZEITBEM.</param>
        /// <param name="kULTUR">kULTUR.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="sORTIERNR">sORTIERNR.</param>
        public AwgWartezeitItems(string aNWENDUNGSBEREICH = default(string), string aWGID = default(string), string aWGWARTEZEITNR = default(string), string eRLAEUTERUNG = default(string), string gESETZTWARTEZEIT = default(string), string gESETZTWARTEZEITBEM = default(string), string kULTUR = default(string), string mROW = default(string), string sORTIERNR = default(string))
        {
            this.ANWENDUNGSBEREICH = aNWENDUNGSBEREICH;
            this.AWG_ID = aWGID;
            this.AWG_WARTEZEIT_NR = aWGWARTEZEITNR;
            this.ERLAEUTERUNG = eRLAEUTERUNG;
            this.GESETZT_WARTEZEIT = gESETZTWARTEZEIT;
            this.GESETZT_WARTEZEIT_BEM = gESETZTWARTEZEITBEM;
            this.KULTUR = kULTUR;
            this.M_ROW = mROW;
            this.SORTIER_NR = sORTIERNR;
        }

        /// <summary>
        /// Gets or Sets ANWENDUNGSBEREICH
        /// </summary>
        [DataMember(Name = "ANWENDUNGSBEREICH", EmitDefaultValue = false)]
        public string ANWENDUNGSBEREICH { get; set; }

        /// <summary>
        /// Gets or Sets AWG_ID
        /// </summary>
        [DataMember(Name = "AWG_ID", EmitDefaultValue = false)]
        public string AWG_ID { get; set; }

        /// <summary>
        /// Gets or Sets AWG_WARTEZEIT_NR
        /// </summary>
        [DataMember(Name = "AWG_WARTEZEIT_NR", EmitDefaultValue = false)]
        public string AWG_WARTEZEIT_NR { get; set; }

        /// <summary>
        /// Gets or Sets ERLAEUTERUNG
        /// </summary>
        [DataMember(Name = "ERLAEUTERUNG", EmitDefaultValue = false)]
        public string ERLAEUTERUNG { get; set; }

        /// <summary>
        /// Gets or Sets GESETZT_WARTEZEIT
        /// </summary>
        [DataMember(Name = "GESETZT_WARTEZEIT", EmitDefaultValue = false)]
        public string GESETZT_WARTEZEIT { get; set; }

        /// <summary>
        /// Gets or Sets GESETZT_WARTEZEIT_BEM
        /// </summary>
        [DataMember(Name = "GESETZT_WARTEZEIT_BEM", EmitDefaultValue = false)]
        public string GESETZT_WARTEZEIT_BEM { get; set; }

        /// <summary>
        /// Gets or Sets KULTUR
        /// </summary>
        [DataMember(Name = "KULTUR", EmitDefaultValue = false)]
        public string KULTUR { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets SORTIER_NR
        /// </summary>
        [DataMember(Name = "SORTIER_NR", EmitDefaultValue = false)]
        public string SORTIER_NR { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AwgWartezeitItems {\n");
            sb.Append("  ANWENDUNGSBEREICH: ").Append(ANWENDUNGSBEREICH).Append("\n");
            sb.Append("  AWG_ID: ").Append(AWG_ID).Append("\n");
            sb.Append("  AWG_WARTEZEIT_NR: ").Append(AWG_WARTEZEIT_NR).Append("\n");
            sb.Append("  ERLAEUTERUNG: ").Append(ERLAEUTERUNG).Append("\n");
            sb.Append("  GESETZT_WARTEZEIT: ").Append(GESETZT_WARTEZEIT).Append("\n");
            sb.Append("  GESETZT_WARTEZEIT_BEM: ").Append(GESETZT_WARTEZEIT_BEM).Append("\n");
            sb.Append("  KULTUR: ").Append(KULTUR).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  SORTIER_NR: ").Append(SORTIER_NR).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AwgWartezeitItems);
        }

        /// <summary>
        /// Returns true if AwgWartezeitItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AwgWartezeitItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AwgWartezeitItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ANWENDUNGSBEREICH == input.ANWENDUNGSBEREICH ||
                    (this.ANWENDUNGSBEREICH != null &&
                    this.ANWENDUNGSBEREICH.Equals(input.ANWENDUNGSBEREICH))
                ) && 
                (
                    this.AWG_ID == input.AWG_ID ||
                    (this.AWG_ID != null &&
                    this.AWG_ID.Equals(input.AWG_ID))
                ) && 
                (
                    this.AWG_WARTEZEIT_NR == input.AWG_WARTEZEIT_NR ||
                    (this.AWG_WARTEZEIT_NR != null &&
                    this.AWG_WARTEZEIT_NR.Equals(input.AWG_WARTEZEIT_NR))
                ) && 
                (
                    this.ERLAEUTERUNG == input.ERLAEUTERUNG ||
                    (this.ERLAEUTERUNG != null &&
                    this.ERLAEUTERUNG.Equals(input.ERLAEUTERUNG))
                ) && 
                (
                    this.GESETZT_WARTEZEIT == input.GESETZT_WARTEZEIT ||
                    (this.GESETZT_WARTEZEIT != null &&
                    this.GESETZT_WARTEZEIT.Equals(input.GESETZT_WARTEZEIT))
                ) && 
                (
                    this.GESETZT_WARTEZEIT_BEM == input.GESETZT_WARTEZEIT_BEM ||
                    (this.GESETZT_WARTEZEIT_BEM != null &&
                    this.GESETZT_WARTEZEIT_BEM.Equals(input.GESETZT_WARTEZEIT_BEM))
                ) && 
                (
                    this.KULTUR == input.KULTUR ||
                    (this.KULTUR != null &&
                    this.KULTUR.Equals(input.KULTUR))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.SORTIER_NR == input.SORTIER_NR ||
                    (this.SORTIER_NR != null &&
                    this.SORTIER_NR.Equals(input.SORTIER_NR))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ANWENDUNGSBEREICH != null)
                    hashCode = hashCode * 59 + this.ANWENDUNGSBEREICH.GetHashCode();
                if (this.AWG_ID != null)
                    hashCode = hashCode * 59 + this.AWG_ID.GetHashCode();
                if (this.AWG_WARTEZEIT_NR != null)
                    hashCode = hashCode * 59 + this.AWG_WARTEZEIT_NR.GetHashCode();
                if (this.ERLAEUTERUNG != null)
                    hashCode = hashCode * 59 + this.ERLAEUTERUNG.GetHashCode();
                if (this.GESETZT_WARTEZEIT != null)
                    hashCode = hashCode * 59 + this.GESETZT_WARTEZEIT.GetHashCode();
                if (this.GESETZT_WARTEZEIT_BEM != null)
                    hashCode = hashCode * 59 + this.GESETZT_WARTEZEIT_BEM.GetHashCode();
                if (this.KULTUR != null)
                    hashCode = hashCode * 59 + this.KULTUR.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.SORTIER_NR != null)
                    hashCode = hashCode * 59 + this.SORTIER_NR.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
