/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// AwgWartezeitAusgKulturItems
    /// </summary>
    [DataContract(Name = "Awg_Wartezeit_Ausg_Kultur_items")]
    public partial class AwgWartezeitAusgKulturItems : IEquatable<AwgWartezeitAusgKulturItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AwgWartezeitAusgKulturItems" /> class.
        /// </summary>
        /// <param name="aWGWARTEZEITNR">aWGWARTEZEITNR.</param>
        /// <param name="kULTUR">kULTUR.</param>
        /// <param name="mROW">mROW.</param>
        public AwgWartezeitAusgKulturItems(string aWGWARTEZEITNR = default(string), string kULTUR = default(string), string mROW = default(string))
        {
            this.AWG_WARTEZEIT_NR = aWGWARTEZEITNR;
            this.KULTUR = kULTUR;
            this.M_ROW = mROW;
        }

        /// <summary>
        /// Gets or Sets AWG_WARTEZEIT_NR
        /// </summary>
        [DataMember(Name = "AWG_WARTEZEIT_NR", EmitDefaultValue = false)]
        public string AWG_WARTEZEIT_NR { get; set; }

        /// <summary>
        /// Gets or Sets KULTUR
        /// </summary>
        [DataMember(Name = "KULTUR", EmitDefaultValue = false)]
        public string KULTUR { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AwgWartezeitAusgKulturItems {\n");
            sb.Append("  AWG_WARTEZEIT_NR: ").Append(AWG_WARTEZEIT_NR).Append("\n");
            sb.Append("  KULTUR: ").Append(KULTUR).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AwgWartezeitAusgKulturItems);
        }

        /// <summary>
        /// Returns true if AwgWartezeitAusgKulturItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AwgWartezeitAusgKulturItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AwgWartezeitAusgKulturItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AWG_WARTEZEIT_NR == input.AWG_WARTEZEIT_NR ||
                    (this.AWG_WARTEZEIT_NR != null &&
                    this.AWG_WARTEZEIT_NR.Equals(input.AWG_WARTEZEIT_NR))
                ) && 
                (
                    this.KULTUR == input.KULTUR ||
                    (this.KULTUR != null &&
                    this.KULTUR.Equals(input.KULTUR))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AWG_WARTEZEIT_NR != null)
                    hashCode = hashCode * 59 + this.AWG_WARTEZEIT_NR.GetHashCode();
                if (this.KULTUR != null)
                    hashCode = hashCode * 59 + this.KULTUR.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
