/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// AwgZulassungItems
    /// </summary>
    [DataContract(Name = "Awg_Zulassung_items")]
    public partial class AwgZulassungItems : IEquatable<AwgZulassungItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AwgZulassungItems" /> class.
        /// </summary>
        /// <param name="aWGID">aWGID.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="zULENDE">zULENDE.</param>
        public AwgZulassungItems(string aWGID = default(string), string mROW = default(string), DateTime zULENDE = default(DateTime))
        {
            this.AWG_ID = aWGID;
            this.M_ROW = mROW;
            this.ZUL_ENDE = zULENDE;
        }

        /// <summary>
        /// Gets or Sets AWG_ID
        /// </summary>
        [DataMember(Name = "AWG_ID", EmitDefaultValue = false)]
        public string AWG_ID { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets ZUL_ENDE
        /// </summary>
        [DataMember(Name = "ZUL_ENDE", EmitDefaultValue = false)]
        public DateTime ZUL_ENDE { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AwgZulassungItems {\n");
            sb.Append("  AWG_ID: ").Append(AWG_ID).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  ZUL_ENDE: ").Append(ZUL_ENDE).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AwgZulassungItems);
        }

        /// <summary>
        /// Returns true if AwgZulassungItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AwgZulassungItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AwgZulassungItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AWG_ID == input.AWG_ID ||
                    (this.AWG_ID != null &&
                    this.AWG_ID.Equals(input.AWG_ID))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.ZUL_ENDE == input.ZUL_ENDE ||
                    (this.ZUL_ENDE != null &&
                    this.ZUL_ENDE.Equals(input.ZUL_ENDE))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AWG_ID != null)
                    hashCode = hashCode * 59 + this.AWG_ID.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.ZUL_ENDE != null)
                    hashCode = hashCode * 59 + this.ZUL_ENDE.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
