/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// AwgZeitpunktItems
    /// </summary>
    [DataContract(Name = "Awg_Zeitpunkt_items")]
    public partial class AwgZeitpunktItems : IEquatable<AwgZeitpunktItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AwgZeitpunktItems" /> class.
        /// </summary>
        /// <param name="aWGID">aWGID.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="oPERANDZUVORHER">oPERANDZUVORHER.</param>
        /// <param name="sORTIERNR">sORTIERNR.</param>
        /// <param name="zEITPUNKT">zEITPUNKT.</param>
        public AwgZeitpunktItems(string aWGID = default(string), string mROW = default(string), string oPERANDZUVORHER = default(string), string sORTIERNR = default(string), string zEITPUNKT = default(string))
        {
            this.AWG_ID = aWGID;
            this.M_ROW = mROW;
            this.OPERAND_ZU_VORHER = oPERANDZUVORHER;
            this.SORTIER_NR = sORTIERNR;
            this.ZEITPUNKT = zEITPUNKT;
        }

        /// <summary>
        /// Gets or Sets AWG_ID
        /// </summary>
        [DataMember(Name = "AWG_ID", EmitDefaultValue = false)]
        public string AWG_ID { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets OPERAND_ZU_VORHER
        /// </summary>
        [DataMember(Name = "OPERAND_ZU_VORHER", EmitDefaultValue = false)]
        public string OPERAND_ZU_VORHER { get; set; }

        /// <summary>
        /// Gets or Sets SORTIER_NR
        /// </summary>
        [DataMember(Name = "SORTIER_NR", EmitDefaultValue = false)]
        public string SORTIER_NR { get; set; }

        /// <summary>
        /// Gets or Sets ZEITPUNKT
        /// </summary>
        [DataMember(Name = "ZEITPUNKT", EmitDefaultValue = false)]
        public string ZEITPUNKT { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AwgZeitpunktItems {\n");
            sb.Append("  AWG_ID: ").Append(AWG_ID).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  OPERAND_ZU_VORHER: ").Append(OPERAND_ZU_VORHER).Append("\n");
            sb.Append("  SORTIER_NR: ").Append(SORTIER_NR).Append("\n");
            sb.Append("  ZEITPUNKT: ").Append(ZEITPUNKT).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AwgZeitpunktItems);
        }

        /// <summary>
        /// Returns true if AwgZeitpunktItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AwgZeitpunktItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AwgZeitpunktItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AWG_ID == input.AWG_ID ||
                    (this.AWG_ID != null &&
                    this.AWG_ID.Equals(input.AWG_ID))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.OPERAND_ZU_VORHER == input.OPERAND_ZU_VORHER ||
                    (this.OPERAND_ZU_VORHER != null &&
                    this.OPERAND_ZU_VORHER.Equals(input.OPERAND_ZU_VORHER))
                ) && 
                (
                    this.SORTIER_NR == input.SORTIER_NR ||
                    (this.SORTIER_NR != null &&
                    this.SORTIER_NR.Equals(input.SORTIER_NR))
                ) && 
                (
                    this.ZEITPUNKT == input.ZEITPUNKT ||
                    (this.ZEITPUNKT != null &&
                    this.ZEITPUNKT.Equals(input.ZEITPUNKT))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AWG_ID != null)
                    hashCode = hashCode * 59 + this.AWG_ID.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.OPERAND_ZU_VORHER != null)
                    hashCode = hashCode * 59 + this.OPERAND_ZU_VORHER.GetHashCode();
                if (this.SORTIER_NR != null)
                    hashCode = hashCode * 59 + this.SORTIER_NR.GetHashCode();
                if (this.ZEITPUNKT != null)
                    hashCode = hashCode * 59 + this.ZEITPUNKT.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
