/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// GhsGefahrensymboleItems
    /// </summary>
    [DataContract(Name = "Ghs_Gefahrensymbole_items")]
    public partial class GhsGefahrensymboleItems : IEquatable<GhsGefahrensymboleItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GhsGefahrensymboleItems" /> class.
        /// </summary>
        /// <param name="gEFAHRENSYMBOL">gEFAHRENSYMBOL.</param>
        /// <param name="kENNR">kENNR.</param>
        /// <param name="mROW">mROW.</param>
        public GhsGefahrensymboleItems(string gEFAHRENSYMBOL = default(string), string kENNR = default(string), string mROW = default(string))
        {
            this.GEFAHRENSYMBOL = gEFAHRENSYMBOL;
            this.KENNR = kENNR;
            this.M_ROW = mROW;
        }

        /// <summary>
        /// Gets or Sets GEFAHRENSYMBOL
        /// </summary>
        [DataMember(Name = "GEFAHRENSYMBOL", EmitDefaultValue = false)]
        public string GEFAHRENSYMBOL { get; set; }

        /// <summary>
        /// Gets or Sets KENNR
        /// </summary>
        [DataMember(Name = "KENNR", EmitDefaultValue = false)]
        public string KENNR { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GhsGefahrensymboleItems {\n");
            sb.Append("  GEFAHRENSYMBOL: ").Append(GEFAHRENSYMBOL).Append("\n");
            sb.Append("  KENNR: ").Append(KENNR).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GhsGefahrensymboleItems);
        }

        /// <summary>
        /// Returns true if GhsGefahrensymboleItems instances are equal
        /// </summary>
        /// <param name="input">Instance of GhsGefahrensymboleItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GhsGefahrensymboleItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GEFAHRENSYMBOL == input.GEFAHRENSYMBOL ||
                    (this.GEFAHRENSYMBOL != null &&
                    this.GEFAHRENSYMBOL.Equals(input.GEFAHRENSYMBOL))
                ) && 
                (
                    this.KENNR == input.KENNR ||
                    (this.KENNR != null &&
                    this.KENNR.Equals(input.KENNR))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GEFAHRENSYMBOL != null)
                    hashCode = hashCode * 59 + this.GEFAHRENSYMBOL.GetHashCode();
                if (this.KENNR != null)
                    hashCode = hashCode * 59 + this.KENNR.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
