/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// HinweisItems
    /// </summary>
    [DataContract(Name = "Hinweis_items")]
    public partial class HinweisItems : IEquatable<HinweisItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HinweisItems" /> class.
        /// </summary>
        /// <param name="eBENE">eBENE.</param>
        /// <param name="hINWEIS">hINWEIS.</param>
        /// <param name="mROW">mROW.</param>
        public HinweisItems(string eBENE = default(string), string hINWEIS = default(string), string mROW = default(string))
        {
            this.EBENE = eBENE;
            this.HINWEIS = hINWEIS;
            this.M_ROW = mROW;
        }

        /// <summary>
        /// Gets or Sets EBENE
        /// </summary>
        [DataMember(Name = "EBENE", EmitDefaultValue = false)]
        public string EBENE { get; set; }

        /// <summary>
        /// Gets or Sets HINWEIS
        /// </summary>
        [DataMember(Name = "HINWEIS", EmitDefaultValue = false)]
        public string HINWEIS { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HinweisItems {\n");
            sb.Append("  EBENE: ").Append(EBENE).Append("\n");
            sb.Append("  HINWEIS: ").Append(HINWEIS).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HinweisItems);
        }

        /// <summary>
        /// Returns true if HinweisItems instances are equal
        /// </summary>
        /// <param name="input">Instance of HinweisItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HinweisItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EBENE == input.EBENE ||
                    (this.EBENE != null &&
                    this.EBENE.Equals(input.EBENE))
                ) && 
                (
                    this.HINWEIS == input.HINWEIS ||
                    (this.HINWEIS != null &&
                    this.HINWEIS.Equals(input.HINWEIS))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EBENE != null)
                    hashCode = hashCode * 59 + this.EBENE.GetHashCode();
                if (this.HINWEIS != null)
                    hashCode = hashCode * 59 + this.HINWEIS.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
