/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// KodelisteItems
    /// </summary>
    [DataContract(Name = "Kodeliste_items")]
    public partial class KodelisteItems : IEquatable<KodelisteItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KodelisteItems" /> class.
        /// </summary>
        /// <param name="kODELISTE">kODELISTE.</param>
        /// <param name="lISTENNAME">lISTENNAME.</param>
        public KodelisteItems(string kODELISTE = default(string), string lISTENNAME = default(string))
        {
            this.KODELISTE = kODELISTE;
            this.LISTENNAME = lISTENNAME;
        }

        /// <summary>
        /// Gets or Sets KODELISTE
        /// </summary>
        [DataMember(Name = "KODELISTE", EmitDefaultValue = false)]
        public string KODELISTE { get; set; }

        /// <summary>
        /// Gets or Sets LISTENNAME
        /// </summary>
        [DataMember(Name = "LISTENNAME", EmitDefaultValue = false)]
        public string LISTENNAME { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KodelisteItems {\n");
            sb.Append("  KODELISTE: ").Append(KODELISTE).Append("\n");
            sb.Append("  LISTENNAME: ").Append(LISTENNAME).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as KodelisteItems);
        }

        /// <summary>
        /// Returns true if KodelisteItems instances are equal
        /// </summary>
        /// <param name="input">Instance of KodelisteItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KodelisteItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.KODELISTE == input.KODELISTE ||
                    (this.KODELISTE != null &&
                    this.KODELISTE.Equals(input.KODELISTE))
                ) && 
                (
                    this.LISTENNAME == input.LISTENNAME ||
                    (this.LISTENNAME != null &&
                    this.LISTENNAME.Equals(input.LISTENNAME))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.KODELISTE != null)
                    hashCode = hashCode * 59 + this.KODELISTE.GetHashCode();
                if (this.LISTENNAME != null)
                    hashCode = hashCode * 59 + this.LISTENNAME.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
