/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// KodeItems
    /// </summary>
    [DataContract(Name = "Kode_items")]
    public partial class KodeItems : IEquatable<KodeItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KodeItems" /> class.
        /// </summary>
        /// <param name="kODE">kODE.</param>
        /// <param name="kODELISTE">kODELISTE.</param>
        /// <param name="kODETEXT">kODETEXT.</param>
        /// <param name="sPERRE">sPERRE.</param>
        /// <param name="sPRACHE">sPRACHE.</param>
        public KodeItems(string kODE = default(string), string kODELISTE = default(string), string kODETEXT = default(string), string sPERRE = default(string), string sPRACHE = default(string))
        {
            this.KODE = kODE;
            this.KODELISTE = kODELISTE;
            this.KODETEXT = kODETEXT;
            this.SPERRE = sPERRE;
            this.SPRACHE = sPRACHE;
        }

        /// <summary>
        /// Gets or Sets KODE
        /// </summary>
        [DataMember(Name = "KODE", EmitDefaultValue = false)]
        public string KODE { get; set; }

        /// <summary>
        /// Gets or Sets KODELISTE
        /// </summary>
        [DataMember(Name = "KODELISTE", EmitDefaultValue = false)]
        public string KODELISTE { get; set; }

        /// <summary>
        /// Gets or Sets KODETEXT
        /// </summary>
        [DataMember(Name = "KODETEXT", EmitDefaultValue = false)]
        public string KODETEXT { get; set; }

        /// <summary>
        /// Gets or Sets SPERRE
        /// </summary>
        [DataMember(Name = "SPERRE", EmitDefaultValue = false)]
        public string SPERRE { get; set; }

        /// <summary>
        /// Gets or Sets SPRACHE
        /// </summary>
        [DataMember(Name = "SPRACHE", EmitDefaultValue = false)]
        public string SPRACHE { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KodeItems {\n");
            sb.Append("  KODE: ").Append(KODE).Append("\n");
            sb.Append("  KODELISTE: ").Append(KODELISTE).Append("\n");
            sb.Append("  KODETEXT: ").Append(KODETEXT).Append("\n");
            sb.Append("  SPERRE: ").Append(SPERRE).Append("\n");
            sb.Append("  SPRACHE: ").Append(SPRACHE).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as KodeItems);
        }

        /// <summary>
        /// Returns true if KodeItems instances are equal
        /// </summary>
        /// <param name="input">Instance of KodeItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KodeItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.KODE == input.KODE ||
                    (this.KODE != null &&
                    this.KODE.Equals(input.KODE))
                ) && 
                (
                    this.KODELISTE == input.KODELISTE ||
                    (this.KODELISTE != null &&
                    this.KODELISTE.Equals(input.KODELISTE))
                ) && 
                (
                    this.KODETEXT == input.KODETEXT ||
                    (this.KODETEXT != null &&
                    this.KODETEXT.Equals(input.KODETEXT))
                ) && 
                (
                    this.SPERRE == input.SPERRE ||
                    (this.SPERRE != null &&
                    this.SPERRE.Equals(input.SPERRE))
                ) && 
                (
                    this.SPRACHE == input.SPRACHE ||
                    (this.SPRACHE != null &&
                    this.SPRACHE.Equals(input.SPRACHE))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.KODE != null)
                    hashCode = hashCode * 59 + this.KODE.GetHashCode();
                if (this.KODELISTE != null)
                    hashCode = hashCode * 59 + this.KODELISTE.GetHashCode();
                if (this.KODETEXT != null)
                    hashCode = hashCode * 59 + this.KODETEXT.GetHashCode();
                if (this.SPERRE != null)
                    hashCode = hashCode * 59 + this.SPERRE.GetHashCode();
                if (this.SPRACHE != null)
                    hashCode = hashCode * 59 + this.SPRACHE.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
