/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// KodelisteFeldnameItems
    /// </summary>
    [DataContract(Name = "Kodeliste_Feldname_items")]
    public partial class KodelisteFeldnameItems : IEquatable<KodelisteFeldnameItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KodelisteFeldnameItems" /> class.
        /// </summary>
        /// <param name="fELDNAME">fELDNAME.</param>
        /// <param name="kODELISTE">kODELISTE.</param>
        /// <param name="tABELLE">tABELLE.</param>
        public KodelisteFeldnameItems(string fELDNAME = default(string), string kODELISTE = default(string), string tABELLE = default(string))
        {
            this.FELDNAME = fELDNAME;
            this.KODELISTE = kODELISTE;
            this.TABELLE = tABELLE;
        }

        /// <summary>
        /// Gets or Sets FELDNAME
        /// </summary>
        [DataMember(Name = "FELDNAME", EmitDefaultValue = false)]
        public string FELDNAME { get; set; }

        /// <summary>
        /// Gets or Sets KODELISTE
        /// </summary>
        [DataMember(Name = "KODELISTE", EmitDefaultValue = false)]
        public string KODELISTE { get; set; }

        /// <summary>
        /// Gets or Sets TABELLE
        /// </summary>
        [DataMember(Name = "TABELLE", EmitDefaultValue = false)]
        public string TABELLE { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KodelisteFeldnameItems {\n");
            sb.Append("  FELDNAME: ").Append(FELDNAME).Append("\n");
            sb.Append("  KODELISTE: ").Append(KODELISTE).Append("\n");
            sb.Append("  TABELLE: ").Append(TABELLE).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as KodelisteFeldnameItems);
        }

        /// <summary>
        /// Returns true if KodelisteFeldnameItems instances are equal
        /// </summary>
        /// <param name="input">Instance of KodelisteFeldnameItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KodelisteFeldnameItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FELDNAME == input.FELDNAME ||
                    (this.FELDNAME != null &&
                    this.FELDNAME.Equals(input.FELDNAME))
                ) && 
                (
                    this.KODELISTE == input.KODELISTE ||
                    (this.KODELISTE != null &&
                    this.KODELISTE.Equals(input.KODELISTE))
                ) && 
                (
                    this.TABELLE == input.TABELLE ||
                    (this.TABELLE != null &&
                    this.TABELLE.Equals(input.TABELLE))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FELDNAME != null)
                    hashCode = hashCode * 59 + this.FELDNAME.GetHashCode();
                if (this.KODELISTE != null)
                    hashCode = hashCode * 59 + this.KODELISTE.GetHashCode();
                if (this.TABELLE != null)
                    hashCode = hashCode * 59 + this.TABELLE.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
