/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// MittelAbpackungItems
    /// </summary>
    [DataContract(Name = "Mittel_Abpackung_items")]
    public partial class MittelAbpackungItems : IEquatable<MittelAbpackungItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MittelAbpackungItems" /> class.
        /// </summary>
        /// <param name="aNZAHL">aNZAHL.</param>
        /// <param name="iNHALTEINHEIT">iNHALTEINHEIT.</param>
        /// <param name="kENNR">kENNR.</param>
        /// <param name="mENGE">mENGE.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="nICHTBERUFLICHEANWENDER">nICHTBERUFLICHEANWENDER.</param>
        /// <param name="vERPACKUNGSART">vERPACKUNGSART.</param>
        /// <param name="vERPACKUNGSMATERIAL">vERPACKUNGSMATERIAL.</param>
        public MittelAbpackungItems(string aNZAHL = default(string), string iNHALTEINHEIT = default(string), string kENNR = default(string), string mENGE = default(string), string mROW = default(string), string nICHTBERUFLICHEANWENDER = default(string), string vERPACKUNGSART = default(string), string vERPACKUNGSMATERIAL = default(string))
        {
            this.ANZAHL = aNZAHL;
            this.INHALT_EINHEIT = iNHALTEINHEIT;
            this.KENNR = kENNR;
            this.MENGE = mENGE;
            this.M_ROW = mROW;
            this.NICHTBERUFLICHE_ANWENDER = nICHTBERUFLICHEANWENDER;
            this.VERPACKUNGSART = vERPACKUNGSART;
            this.VERPACKUNGSMATERIAL = vERPACKUNGSMATERIAL;
        }

        /// <summary>
        /// Gets or Sets ANZAHL
        /// </summary>
        [DataMember(Name = "ANZAHL", EmitDefaultValue = false)]
        public string ANZAHL { get; set; }

        /// <summary>
        /// Gets or Sets INHALT_EINHEIT
        /// </summary>
        [DataMember(Name = "INHALT_EINHEIT", EmitDefaultValue = false)]
        public string INHALT_EINHEIT { get; set; }

        /// <summary>
        /// Gets or Sets KENNR
        /// </summary>
        [DataMember(Name = "KENNR", EmitDefaultValue = false)]
        public string KENNR { get; set; }

        /// <summary>
        /// Gets or Sets MENGE
        /// </summary>
        [DataMember(Name = "MENGE", EmitDefaultValue = false)]
        public string MENGE { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets NICHTBERUFLICHE_ANWENDER
        /// </summary>
        [DataMember(Name = "NICHTBERUFLICHE_ANWENDER", EmitDefaultValue = false)]
        public string NICHTBERUFLICHE_ANWENDER { get; set; }

        /// <summary>
        /// Gets or Sets VERPACKUNGSART
        /// </summary>
        [DataMember(Name = "VERPACKUNGSART", EmitDefaultValue = false)]
        public string VERPACKUNGSART { get; set; }

        /// <summary>
        /// Gets or Sets VERPACKUNGSMATERIAL
        /// </summary>
        [DataMember(Name = "VERPACKUNGSMATERIAL", EmitDefaultValue = false)]
        public string VERPACKUNGSMATERIAL { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MittelAbpackungItems {\n");
            sb.Append("  ANZAHL: ").Append(ANZAHL).Append("\n");
            sb.Append("  INHALT_EINHEIT: ").Append(INHALT_EINHEIT).Append("\n");
            sb.Append("  KENNR: ").Append(KENNR).Append("\n");
            sb.Append("  MENGE: ").Append(MENGE).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  NICHTBERUFLICHE_ANWENDER: ").Append(NICHTBERUFLICHE_ANWENDER).Append("\n");
            sb.Append("  VERPACKUNGSART: ").Append(VERPACKUNGSART).Append("\n");
            sb.Append("  VERPACKUNGSMATERIAL: ").Append(VERPACKUNGSMATERIAL).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MittelAbpackungItems);
        }

        /// <summary>
        /// Returns true if MittelAbpackungItems instances are equal
        /// </summary>
        /// <param name="input">Instance of MittelAbpackungItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MittelAbpackungItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ANZAHL == input.ANZAHL ||
                    (this.ANZAHL != null &&
                    this.ANZAHL.Equals(input.ANZAHL))
                ) && 
                (
                    this.INHALT_EINHEIT == input.INHALT_EINHEIT ||
                    (this.INHALT_EINHEIT != null &&
                    this.INHALT_EINHEIT.Equals(input.INHALT_EINHEIT))
                ) && 
                (
                    this.KENNR == input.KENNR ||
                    (this.KENNR != null &&
                    this.KENNR.Equals(input.KENNR))
                ) && 
                (
                    this.MENGE == input.MENGE ||
                    (this.MENGE != null &&
                    this.MENGE.Equals(input.MENGE))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.NICHTBERUFLICHE_ANWENDER == input.NICHTBERUFLICHE_ANWENDER ||
                    (this.NICHTBERUFLICHE_ANWENDER != null &&
                    this.NICHTBERUFLICHE_ANWENDER.Equals(input.NICHTBERUFLICHE_ANWENDER))
                ) && 
                (
                    this.VERPACKUNGSART == input.VERPACKUNGSART ||
                    (this.VERPACKUNGSART != null &&
                    this.VERPACKUNGSART.Equals(input.VERPACKUNGSART))
                ) && 
                (
                    this.VERPACKUNGSMATERIAL == input.VERPACKUNGSMATERIAL ||
                    (this.VERPACKUNGSMATERIAL != null &&
                    this.VERPACKUNGSMATERIAL.Equals(input.VERPACKUNGSMATERIAL))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ANZAHL != null)
                    hashCode = hashCode * 59 + this.ANZAHL.GetHashCode();
                if (this.INHALT_EINHEIT != null)
                    hashCode = hashCode * 59 + this.INHALT_EINHEIT.GetHashCode();
                if (this.KENNR != null)
                    hashCode = hashCode * 59 + this.KENNR.GetHashCode();
                if (this.MENGE != null)
                    hashCode = hashCode * 59 + this.MENGE.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.NICHTBERUFLICHE_ANWENDER != null)
                    hashCode = hashCode * 59 + this.NICHTBERUFLICHE_ANWENDER.GetHashCode();
                if (this.VERPACKUNGSART != null)
                    hashCode = hashCode * 59 + this.VERPACKUNGSART.GetHashCode();
                if (this.VERPACKUNGSMATERIAL != null)
                    hashCode = hashCode * 59 + this.VERPACKUNGSMATERIAL.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
