/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// MittelAbgelaufenItems
    /// </summary>
    [DataContract(Name = "Mittel_Abgelaufen_items")]
    public partial class MittelAbgelaufenItems : IEquatable<MittelAbgelaufenItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MittelAbgelaufenItems" /> class.
        /// </summary>
        /// <param name="aUFBRAUCHFRIST">aUFBRAUCHFRIST.</param>
        /// <param name="fORMULIERUNGART">fORMULIERUNGART.</param>
        /// <param name="kENNR">kENNR.</param>
        /// <param name="mITTELNAME">mITTELNAME.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="sTATUS">sTATUS.</param>
        /// <param name="zULENDE">zULENDE.</param>
        /// <param name="zULERSTMALIGAM">zULERSTMALIGAM.</param>
        public MittelAbgelaufenItems(DateTime aUFBRAUCHFRIST = default(DateTime), string fORMULIERUNGART = default(string), string kENNR = default(string), string mITTELNAME = default(string), string mROW = default(string), string sTATUS = default(string), DateTime zULENDE = default(DateTime), DateTime zULERSTMALIGAM = default(DateTime))
        {
            this.AUFBRAUCHFRIST = aUFBRAUCHFRIST;
            this.FORMULIERUNG_ART = fORMULIERUNGART;
            this.KENNR = kENNR;
            this.MITTELNAME = mITTELNAME;
            this.M_ROW = mROW;
            this.STATUS = sTATUS;
            this.ZUL_ENDE = zULENDE;
            this.ZUL_ERSTMALIG_AM = zULERSTMALIGAM;
        }

        /// <summary>
        /// Gets or Sets AUFBRAUCHFRIST
        /// </summary>
        [DataMember(Name = "AUFBRAUCHFRIST", EmitDefaultValue = false)]
        public DateTime AUFBRAUCHFRIST { get; set; }

        /// <summary>
        /// Gets or Sets FORMULIERUNG_ART
        /// </summary>
        [DataMember(Name = "FORMULIERUNG_ART", EmitDefaultValue = false)]
        public string FORMULIERUNG_ART { get; set; }

        /// <summary>
        /// Gets or Sets KENNR
        /// </summary>
        [DataMember(Name = "KENNR", EmitDefaultValue = false)]
        public string KENNR { get; set; }

        /// <summary>
        /// Gets or Sets MITTELNAME
        /// </summary>
        [DataMember(Name = "MITTELNAME", EmitDefaultValue = false)]
        public string MITTELNAME { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets STATUS
        /// </summary>
        [DataMember(Name = "STATUS", EmitDefaultValue = false)]
        public string STATUS { get; set; }

        /// <summary>
        /// Gets or Sets ZUL_ENDE
        /// </summary>
        [DataMember(Name = "ZUL_ENDE", EmitDefaultValue = false)]
        public DateTime ZUL_ENDE { get; set; }

        /// <summary>
        /// Gets or Sets ZUL_ERSTMALIG_AM
        /// </summary>
        [DataMember(Name = "ZUL_ERSTMALIG_AM", EmitDefaultValue = false)]
        public DateTime ZUL_ERSTMALIG_AM { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MittelAbgelaufenItems {\n");
            sb.Append("  AUFBRAUCHFRIST: ").Append(AUFBRAUCHFRIST).Append("\n");
            sb.Append("  FORMULIERUNG_ART: ").Append(FORMULIERUNG_ART).Append("\n");
            sb.Append("  KENNR: ").Append(KENNR).Append("\n");
            sb.Append("  MITTELNAME: ").Append(MITTELNAME).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  STATUS: ").Append(STATUS).Append("\n");
            sb.Append("  ZUL_ENDE: ").Append(ZUL_ENDE).Append("\n");
            sb.Append("  ZUL_ERSTMALIG_AM: ").Append(ZUL_ERSTMALIG_AM).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MittelAbgelaufenItems);
        }

        /// <summary>
        /// Returns true if MittelAbgelaufenItems instances are equal
        /// </summary>
        /// <param name="input">Instance of MittelAbgelaufenItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MittelAbgelaufenItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AUFBRAUCHFRIST == input.AUFBRAUCHFRIST ||
                    (this.AUFBRAUCHFRIST != null &&
                    this.AUFBRAUCHFRIST.Equals(input.AUFBRAUCHFRIST))
                ) && 
                (
                    this.FORMULIERUNG_ART == input.FORMULIERUNG_ART ||
                    (this.FORMULIERUNG_ART != null &&
                    this.FORMULIERUNG_ART.Equals(input.FORMULIERUNG_ART))
                ) && 
                (
                    this.KENNR == input.KENNR ||
                    (this.KENNR != null &&
                    this.KENNR.Equals(input.KENNR))
                ) && 
                (
                    this.MITTELNAME == input.MITTELNAME ||
                    (this.MITTELNAME != null &&
                    this.MITTELNAME.Equals(input.MITTELNAME))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.STATUS == input.STATUS ||
                    (this.STATUS != null &&
                    this.STATUS.Equals(input.STATUS))
                ) && 
                (
                    this.ZUL_ENDE == input.ZUL_ENDE ||
                    (this.ZUL_ENDE != null &&
                    this.ZUL_ENDE.Equals(input.ZUL_ENDE))
                ) && 
                (
                    this.ZUL_ERSTMALIG_AM == input.ZUL_ERSTMALIG_AM ||
                    (this.ZUL_ERSTMALIG_AM != null &&
                    this.ZUL_ERSTMALIG_AM.Equals(input.ZUL_ERSTMALIG_AM))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AUFBRAUCHFRIST != null)
                    hashCode = hashCode * 59 + this.AUFBRAUCHFRIST.GetHashCode();
                if (this.FORMULIERUNG_ART != null)
                    hashCode = hashCode * 59 + this.FORMULIERUNG_ART.GetHashCode();
                if (this.KENNR != null)
                    hashCode = hashCode * 59 + this.KENNR.GetHashCode();
                if (this.MITTELNAME != null)
                    hashCode = hashCode * 59 + this.MITTELNAME.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.STATUS != null)
                    hashCode = hashCode * 59 + this.STATUS.GetHashCode();
                if (this.ZUL_ENDE != null)
                    hashCode = hashCode * 59 + this.ZUL_ENDE.GetHashCode();
                if (this.ZUL_ERSTMALIG_AM != null)
                    hashCode = hashCode * 59 + this.ZUL_ERSTMALIG_AM.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
