/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// ParallelimportAbgelaufenItems
    /// </summary>
    [DataContract(Name = "Parallelimport_Abgelaufen_items")]
    public partial class ParallelimportAbgelaufenItems : IEquatable<ParallelimportAbgelaufenItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParallelimportAbgelaufenItems" /> class.
        /// </summary>
        /// <param name="bESCHEIDDATUM">bESCHEIDDATUM.</param>
        /// <param name="bESCHEINIGUNG">bESCHEINIGUNG.</param>
        /// <param name="gUELTIG">gUELTIG.</param>
        /// <param name="iMPORTEUR">iMPORTEUR.</param>
        /// <param name="iMPORTEURNR">iMPORTEURNR.</param>
        /// <param name="iMPORTEURTXT">iMPORTEURTXT.</param>
        /// <param name="mITTELNAME">mITTELNAME.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="pIBESCHEIDNR">pIBESCHEIDNR.</param>
        /// <param name="pIKENNZIFFER">pIKENNZIFFER.</param>
        /// <param name="pIMITTELNAME">pIMITTELNAME.</param>
        /// <param name="pIPSMNR">pIPSMNR.</param>
        /// <param name="pIREFERENZKENNR">pIREFERENZKENNR.</param>
        /// <param name="pISTATUS">pISTATUS.</param>
        public ParallelimportAbgelaufenItems(DateTime bESCHEIDDATUM = default(DateTime), string bESCHEINIGUNG = default(string), DateTime gUELTIG = default(DateTime), string iMPORTEUR = default(string), string iMPORTEURNR = default(string), string iMPORTEURTXT = default(string), string mITTELNAME = default(string), string mROW = default(string), string pIBESCHEIDNR = default(string), string pIKENNZIFFER = default(string), string pIMITTELNAME = default(string), string pIPSMNR = default(string), string pIREFERENZKENNR = default(string), string pISTATUS = default(string))
        {
            this.BESCHEID_DATUM = bESCHEIDDATUM;
            this.BESCHEINIGUNG = bESCHEINIGUNG;
            this.GUELTIG = gUELTIG;
            this.IMPORTEUR = iMPORTEUR;
            this.IMPORTEUR_NR = iMPORTEURNR;
            this.IMPORTEUR_TXT = iMPORTEURTXT;
            this.MITTELNAME = mITTELNAME;
            this.M_ROW = mROW;
            this.PI_BESCHEIDNR = pIBESCHEIDNR;
            this.PI_KENNZIFFER = pIKENNZIFFER;
            this.PI_MITTELNAME = pIMITTELNAME;
            this.PI_PSMNR = pIPSMNR;
            this.PI_REFERENZ_KENNR = pIREFERENZKENNR;
            this.PI_STATUS = pISTATUS;
        }

        /// <summary>
        /// Gets or Sets BESCHEID_DATUM
        /// </summary>
        [DataMember(Name = "BESCHEID_DATUM", EmitDefaultValue = false)]
        public DateTime BESCHEID_DATUM { get; set; }

        /// <summary>
        /// Gets or Sets BESCHEINIGUNG
        /// </summary>
        [DataMember(Name = "BESCHEINIGUNG", EmitDefaultValue = false)]
        public string BESCHEINIGUNG { get; set; }

        /// <summary>
        /// Gets or Sets GUELTIG
        /// </summary>
        [DataMember(Name = "GUELTIG", EmitDefaultValue = false)]
        public DateTime GUELTIG { get; set; }

        /// <summary>
        /// Gets or Sets IMPORTEUR
        /// </summary>
        [DataMember(Name = "IMPORTEUR", EmitDefaultValue = false)]
        public string IMPORTEUR { get; set; }

        /// <summary>
        /// Gets or Sets IMPORTEUR_NR
        /// </summary>
        [DataMember(Name = "IMPORTEUR_NR", EmitDefaultValue = false)]
        public string IMPORTEUR_NR { get; set; }

        /// <summary>
        /// Gets or Sets IMPORTEUR_TXT
        /// </summary>
        [DataMember(Name = "IMPORTEUR_TXT", EmitDefaultValue = false)]
        public string IMPORTEUR_TXT { get; set; }

        /// <summary>
        /// Gets or Sets MITTELNAME
        /// </summary>
        [DataMember(Name = "MITTELNAME", EmitDefaultValue = false)]
        public string MITTELNAME { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets PI_BESCHEIDNR
        /// </summary>
        [DataMember(Name = "PI_BESCHEIDNR", EmitDefaultValue = false)]
        public string PI_BESCHEIDNR { get; set; }

        /// <summary>
        /// Gets or Sets PI_KENNZIFFER
        /// </summary>
        [DataMember(Name = "PI_KENNZIFFER", EmitDefaultValue = false)]
        public string PI_KENNZIFFER { get; set; }

        /// <summary>
        /// Gets or Sets PI_MITTELNAME
        /// </summary>
        [DataMember(Name = "PI_MITTELNAME", EmitDefaultValue = false)]
        public string PI_MITTELNAME { get; set; }

        /// <summary>
        /// Gets or Sets PI_PSMNR
        /// </summary>
        [DataMember(Name = "PI_PSMNR", EmitDefaultValue = false)]
        public string PI_PSMNR { get; set; }

        /// <summary>
        /// Gets or Sets PI_REFERENZ_KENNR
        /// </summary>
        [DataMember(Name = "PI_REFERENZ_KENNR", EmitDefaultValue = false)]
        public string PI_REFERENZ_KENNR { get; set; }

        /// <summary>
        /// Gets or Sets PI_STATUS
        /// </summary>
        [DataMember(Name = "PI_STATUS", EmitDefaultValue = false)]
        public string PI_STATUS { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ParallelimportAbgelaufenItems {\n");
            sb.Append("  BESCHEID_DATUM: ").Append(BESCHEID_DATUM).Append("\n");
            sb.Append("  BESCHEINIGUNG: ").Append(BESCHEINIGUNG).Append("\n");
            sb.Append("  GUELTIG: ").Append(GUELTIG).Append("\n");
            sb.Append("  IMPORTEUR: ").Append(IMPORTEUR).Append("\n");
            sb.Append("  IMPORTEUR_NR: ").Append(IMPORTEUR_NR).Append("\n");
            sb.Append("  IMPORTEUR_TXT: ").Append(IMPORTEUR_TXT).Append("\n");
            sb.Append("  MITTELNAME: ").Append(MITTELNAME).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  PI_BESCHEIDNR: ").Append(PI_BESCHEIDNR).Append("\n");
            sb.Append("  PI_KENNZIFFER: ").Append(PI_KENNZIFFER).Append("\n");
            sb.Append("  PI_MITTELNAME: ").Append(PI_MITTELNAME).Append("\n");
            sb.Append("  PI_PSMNR: ").Append(PI_PSMNR).Append("\n");
            sb.Append("  PI_REFERENZ_KENNR: ").Append(PI_REFERENZ_KENNR).Append("\n");
            sb.Append("  PI_STATUS: ").Append(PI_STATUS).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ParallelimportAbgelaufenItems);
        }

        /// <summary>
        /// Returns true if ParallelimportAbgelaufenItems instances are equal
        /// </summary>
        /// <param name="input">Instance of ParallelimportAbgelaufenItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ParallelimportAbgelaufenItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BESCHEID_DATUM == input.BESCHEID_DATUM ||
                    (this.BESCHEID_DATUM != null &&
                    this.BESCHEID_DATUM.Equals(input.BESCHEID_DATUM))
                ) && 
                (
                    this.BESCHEINIGUNG == input.BESCHEINIGUNG ||
                    (this.BESCHEINIGUNG != null &&
                    this.BESCHEINIGUNG.Equals(input.BESCHEINIGUNG))
                ) && 
                (
                    this.GUELTIG == input.GUELTIG ||
                    (this.GUELTIG != null &&
                    this.GUELTIG.Equals(input.GUELTIG))
                ) && 
                (
                    this.IMPORTEUR == input.IMPORTEUR ||
                    (this.IMPORTEUR != null &&
                    this.IMPORTEUR.Equals(input.IMPORTEUR))
                ) && 
                (
                    this.IMPORTEUR_NR == input.IMPORTEUR_NR ||
                    (this.IMPORTEUR_NR != null &&
                    this.IMPORTEUR_NR.Equals(input.IMPORTEUR_NR))
                ) && 
                (
                    this.IMPORTEUR_TXT == input.IMPORTEUR_TXT ||
                    (this.IMPORTEUR_TXT != null &&
                    this.IMPORTEUR_TXT.Equals(input.IMPORTEUR_TXT))
                ) && 
                (
                    this.MITTELNAME == input.MITTELNAME ||
                    (this.MITTELNAME != null &&
                    this.MITTELNAME.Equals(input.MITTELNAME))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.PI_BESCHEIDNR == input.PI_BESCHEIDNR ||
                    (this.PI_BESCHEIDNR != null &&
                    this.PI_BESCHEIDNR.Equals(input.PI_BESCHEIDNR))
                ) && 
                (
                    this.PI_KENNZIFFER == input.PI_KENNZIFFER ||
                    (this.PI_KENNZIFFER != null &&
                    this.PI_KENNZIFFER.Equals(input.PI_KENNZIFFER))
                ) && 
                (
                    this.PI_MITTELNAME == input.PI_MITTELNAME ||
                    (this.PI_MITTELNAME != null &&
                    this.PI_MITTELNAME.Equals(input.PI_MITTELNAME))
                ) && 
                (
                    this.PI_PSMNR == input.PI_PSMNR ||
                    (this.PI_PSMNR != null &&
                    this.PI_PSMNR.Equals(input.PI_PSMNR))
                ) && 
                (
                    this.PI_REFERENZ_KENNR == input.PI_REFERENZ_KENNR ||
                    (this.PI_REFERENZ_KENNR != null &&
                    this.PI_REFERENZ_KENNR.Equals(input.PI_REFERENZ_KENNR))
                ) && 
                (
                    this.PI_STATUS == input.PI_STATUS ||
                    (this.PI_STATUS != null &&
                    this.PI_STATUS.Equals(input.PI_STATUS))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BESCHEID_DATUM != null)
                    hashCode = hashCode * 59 + this.BESCHEID_DATUM.GetHashCode();
                if (this.BESCHEINIGUNG != null)
                    hashCode = hashCode * 59 + this.BESCHEINIGUNG.GetHashCode();
                if (this.GUELTIG != null)
                    hashCode = hashCode * 59 + this.GUELTIG.GetHashCode();
                if (this.IMPORTEUR != null)
                    hashCode = hashCode * 59 + this.IMPORTEUR.GetHashCode();
                if (this.IMPORTEUR_NR != null)
                    hashCode = hashCode * 59 + this.IMPORTEUR_NR.GetHashCode();
                if (this.IMPORTEUR_TXT != null)
                    hashCode = hashCode * 59 + this.IMPORTEUR_TXT.GetHashCode();
                if (this.MITTELNAME != null)
                    hashCode = hashCode * 59 + this.MITTELNAME.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.PI_BESCHEIDNR != null)
                    hashCode = hashCode * 59 + this.PI_BESCHEIDNR.GetHashCode();
                if (this.PI_KENNZIFFER != null)
                    hashCode = hashCode * 59 + this.PI_KENNZIFFER.GetHashCode();
                if (this.PI_MITTELNAME != null)
                    hashCode = hashCode * 59 + this.PI_MITTELNAME.GetHashCode();
                if (this.PI_PSMNR != null)
                    hashCode = hashCode * 59 + this.PI_PSMNR.GetHashCode();
                if (this.PI_REFERENZ_KENNR != null)
                    hashCode = hashCode * 59 + this.PI_REFERENZ_KENNR.GetHashCode();
                if (this.PI_STATUS != null)
                    hashCode = hashCode * 59 + this.PI_STATUS.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
