/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// StandItems
    /// </summary>
    [DataContract(Name = "Stand_items")]
    public partial class StandItems : IEquatable<StandItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StandItems" /> class.
        /// </summary>
        /// <param name="dATUM">dATUM.</param>
        /// <param name="mROW">mROW.</param>
        public StandItems(DateTime dATUM = default(DateTime), string mROW = default(string))
        {
            this.DATUM = dATUM;
            this.M_ROW = mROW;
        }

        /// <summary>
        /// Gets or Sets DATUM
        /// </summary>
        [DataMember(Name = "DATUM", EmitDefaultValue = false)]
        public DateTime DATUM { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StandItems {\n");
            sb.Append("  DATUM: ").Append(DATUM).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StandItems);
        }

        /// <summary>
        /// Returns true if StandItems instances are equal
        /// </summary>
        /// <param name="input">Instance of StandItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StandItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DATUM == input.DATUM ||
                    (this.DATUM != null &&
                    this.DATUM.Equals(input.DATUM))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DATUM != null)
                    hashCode = hashCode * 59 + this.DATUM.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
