/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// WirkstoffItems
    /// </summary>
    [DataContract(Name = "Wirkstoff_items")]
    public partial class WirkstoffItems : IEquatable<WirkstoffItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WirkstoffItems" /> class.
        /// </summary>
        /// <param name="gENEHMIGT">gENEHMIGT.</param>
        /// <param name="kATEGORIE">kATEGORIE.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="wIRKNR">wIRKNR.</param>
        /// <param name="wIRKSTOFFNAME">wIRKSTOFFNAME.</param>
        /// <param name="wIRKSTOFFNAMEEN">wIRKSTOFFNAMEEN.</param>
        public WirkstoffItems(string gENEHMIGT = default(string), string kATEGORIE = default(string), string mROW = default(string), string wIRKNR = default(string), string wIRKSTOFFNAME = default(string), string wIRKSTOFFNAMEEN = default(string))
        {
            this.GENEHMIGT = gENEHMIGT;
            this.KATEGORIE = kATEGORIE;
            this.M_ROW = mROW;
            this.WIRKNR = wIRKNR;
            this.WIRKSTOFFNAME = wIRKSTOFFNAME;
            this.WIRKSTOFFNAME_EN = wIRKSTOFFNAMEEN;
        }

        /// <summary>
        /// Gets or Sets GENEHMIGT
        /// </summary>
        [DataMember(Name = "GENEHMIGT", EmitDefaultValue = false)]
        public string GENEHMIGT { get; set; }

        /// <summary>
        /// Gets or Sets KATEGORIE
        /// </summary>
        [DataMember(Name = "KATEGORIE", EmitDefaultValue = false)]
        public string KATEGORIE { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets WIRKNR
        /// </summary>
        [DataMember(Name = "WIRKNR", EmitDefaultValue = false)]
        public string WIRKNR { get; set; }

        /// <summary>
        /// Gets or Sets WIRKSTOFFNAME
        /// </summary>
        [DataMember(Name = "WIRKSTOFFNAME", EmitDefaultValue = false)]
        public string WIRKSTOFFNAME { get; set; }

        /// <summary>
        /// Gets or Sets WIRKSTOFFNAME_EN
        /// </summary>
        [DataMember(Name = "WIRKSTOFFNAME_EN", EmitDefaultValue = false)]
        public string WIRKSTOFFNAME_EN { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WirkstoffItems {\n");
            sb.Append("  GENEHMIGT: ").Append(GENEHMIGT).Append("\n");
            sb.Append("  KATEGORIE: ").Append(KATEGORIE).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  WIRKNR: ").Append(WIRKNR).Append("\n");
            sb.Append("  WIRKSTOFFNAME: ").Append(WIRKSTOFFNAME).Append("\n");
            sb.Append("  WIRKSTOFFNAME_EN: ").Append(WIRKSTOFFNAME_EN).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WirkstoffItems);
        }

        /// <summary>
        /// Returns true if WirkstoffItems instances are equal
        /// </summary>
        /// <param name="input">Instance of WirkstoffItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WirkstoffItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GENEHMIGT == input.GENEHMIGT ||
                    (this.GENEHMIGT != null &&
                    this.GENEHMIGT.Equals(input.GENEHMIGT))
                ) && 
                (
                    this.KATEGORIE == input.KATEGORIE ||
                    (this.KATEGORIE != null &&
                    this.KATEGORIE.Equals(input.KATEGORIE))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.WIRKNR == input.WIRKNR ||
                    (this.WIRKNR != null &&
                    this.WIRKNR.Equals(input.WIRKNR))
                ) && 
                (
                    this.WIRKSTOFFNAME == input.WIRKSTOFFNAME ||
                    (this.WIRKSTOFFNAME != null &&
                    this.WIRKSTOFFNAME.Equals(input.WIRKSTOFFNAME))
                ) && 
                (
                    this.WIRKSTOFFNAME_EN == input.WIRKSTOFFNAME_EN ||
                    (this.WIRKSTOFFNAME_EN != null &&
                    this.WIRKSTOFFNAME_EN.Equals(input.WIRKSTOFFNAME_EN))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GENEHMIGT != null)
                    hashCode = hashCode * 59 + this.GENEHMIGT.GetHashCode();
                if (this.KATEGORIE != null)
                    hashCode = hashCode * 59 + this.KATEGORIE.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.WIRKNR != null)
                    hashCode = hashCode * 59 + this.WIRKNR.GetHashCode();
                if (this.WIRKSTOFFNAME != null)
                    hashCode = hashCode * 59 + this.WIRKSTOFFNAME.GetHashCode();
                if (this.WIRKSTOFFNAME_EN != null)
                    hashCode = hashCode * 59 + this.WIRKSTOFFNAME_EN.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
