/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = APICrawler.Api.Client.OpenAPIDateConverter;

namespace APICrawler.Api.Model
{
    /// <summary>
    /// WirkstoffGehaltItems
    /// </summary>
    [DataContract(Name = "Wirkstoff_Gehalt_items")]
    public partial class WirkstoffGehaltItems : IEquatable<WirkstoffGehaltItems>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WirkstoffGehaltItems" /> class.
        /// </summary>
        /// <param name="gEHALTBIO">gEHALTBIO.</param>
        /// <param name="gEHALTBIOEINHEIT">gEHALTBIOEINHEIT.</param>
        /// <param name="gEHALTEINHEIT">gEHALTEINHEIT.</param>
        /// <param name="gEHALTREIN">gEHALTREIN.</param>
        /// <param name="gEHALTREINGRUNDSTRUKTUR">gEHALTREINGRUNDSTRUKTUR.</param>
        /// <param name="kENNR">kENNR.</param>
        /// <param name="mROW">mROW.</param>
        /// <param name="wIRKNR">wIRKNR.</param>
        /// <param name="wIRKVAR">wIRKVAR.</param>
        public WirkstoffGehaltItems(string gEHALTBIO = default(string), string gEHALTBIOEINHEIT = default(string), string gEHALTEINHEIT = default(string), string gEHALTREIN = default(string), string gEHALTREINGRUNDSTRUKTUR = default(string), string kENNR = default(string), string mROW = default(string), string wIRKNR = default(string), string wIRKVAR = default(string))
        {
            this.GEHALT_BIO = gEHALTBIO;
            this.GEHALT_BIO_EINHEIT = gEHALTBIOEINHEIT;
            this.GEHALT_EINHEIT = gEHALTEINHEIT;
            this.GEHALT_REIN = gEHALTREIN;
            this.GEHALT_REIN_GRUNDSTRUKTUR = gEHALTREINGRUNDSTRUKTUR;
            this.KENNR = kENNR;
            this.M_ROW = mROW;
            this.WIRKNR = wIRKNR;
            this.WIRKVAR = wIRKVAR;
        }

        /// <summary>
        /// Gets or Sets GEHALT_BIO
        /// </summary>
        [DataMember(Name = "GEHALT_BIO", EmitDefaultValue = false)]
        public string GEHALT_BIO { get; set; }

        /// <summary>
        /// Gets or Sets GEHALT_BIO_EINHEIT
        /// </summary>
        [DataMember(Name = "GEHALT_BIO_EINHEIT", EmitDefaultValue = false)]
        public string GEHALT_BIO_EINHEIT { get; set; }

        /// <summary>
        /// Gets or Sets GEHALT_EINHEIT
        /// </summary>
        [DataMember(Name = "GEHALT_EINHEIT", EmitDefaultValue = false)]
        public string GEHALT_EINHEIT { get; set; }

        /// <summary>
        /// Gets or Sets GEHALT_REIN
        /// </summary>
        [DataMember(Name = "GEHALT_REIN", EmitDefaultValue = false)]
        public string GEHALT_REIN { get; set; }

        /// <summary>
        /// Gets or Sets GEHALT_REIN_GRUNDSTRUKTUR
        /// </summary>
        [DataMember(Name = "GEHALT_REIN_GRUNDSTRUKTUR", EmitDefaultValue = false)]
        public string GEHALT_REIN_GRUNDSTRUKTUR { get; set; }

        /// <summary>
        /// Gets or Sets KENNR
        /// </summary>
        [DataMember(Name = "KENNR", EmitDefaultValue = false)]
        public string KENNR { get; set; }

        /// <summary>
        /// Gets or Sets M_ROW
        /// </summary>
        [DataMember(Name = "M_ROW$$", EmitDefaultValue = false)]
        public string M_ROW { get; set; }

        /// <summary>
        /// Gets or Sets WIRKNR
        /// </summary>
        [DataMember(Name = "WIRKNR", EmitDefaultValue = false)]
        public string WIRKNR { get; set; }

        /// <summary>
        /// Gets or Sets WIRKVAR
        /// </summary>
        [DataMember(Name = "WIRKVAR", EmitDefaultValue = false)]
        public string WIRKVAR { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WirkstoffGehaltItems {\n");
            sb.Append("  GEHALT_BIO: ").Append(GEHALT_BIO).Append("\n");
            sb.Append("  GEHALT_BIO_EINHEIT: ").Append(GEHALT_BIO_EINHEIT).Append("\n");
            sb.Append("  GEHALT_EINHEIT: ").Append(GEHALT_EINHEIT).Append("\n");
            sb.Append("  GEHALT_REIN: ").Append(GEHALT_REIN).Append("\n");
            sb.Append("  GEHALT_REIN_GRUNDSTRUKTUR: ").Append(GEHALT_REIN_GRUNDSTRUKTUR).Append("\n");
            sb.Append("  KENNR: ").Append(KENNR).Append("\n");
            sb.Append("  M_ROW: ").Append(M_ROW).Append("\n");
            sb.Append("  WIRKNR: ").Append(WIRKNR).Append("\n");
            sb.Append("  WIRKVAR: ").Append(WIRKVAR).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WirkstoffGehaltItems);
        }

        /// <summary>
        /// Returns true if WirkstoffGehaltItems instances are equal
        /// </summary>
        /// <param name="input">Instance of WirkstoffGehaltItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WirkstoffGehaltItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GEHALT_BIO == input.GEHALT_BIO ||
                    (this.GEHALT_BIO != null &&
                    this.GEHALT_BIO.Equals(input.GEHALT_BIO))
                ) && 
                (
                    this.GEHALT_BIO_EINHEIT == input.GEHALT_BIO_EINHEIT ||
                    (this.GEHALT_BIO_EINHEIT != null &&
                    this.GEHALT_BIO_EINHEIT.Equals(input.GEHALT_BIO_EINHEIT))
                ) && 
                (
                    this.GEHALT_EINHEIT == input.GEHALT_EINHEIT ||
                    (this.GEHALT_EINHEIT != null &&
                    this.GEHALT_EINHEIT.Equals(input.GEHALT_EINHEIT))
                ) && 
                (
                    this.GEHALT_REIN == input.GEHALT_REIN ||
                    (this.GEHALT_REIN != null &&
                    this.GEHALT_REIN.Equals(input.GEHALT_REIN))
                ) && 
                (
                    this.GEHALT_REIN_GRUNDSTRUKTUR == input.GEHALT_REIN_GRUNDSTRUKTUR ||
                    (this.GEHALT_REIN_GRUNDSTRUKTUR != null &&
                    this.GEHALT_REIN_GRUNDSTRUKTUR.Equals(input.GEHALT_REIN_GRUNDSTRUKTUR))
                ) && 
                (
                    this.KENNR == input.KENNR ||
                    (this.KENNR != null &&
                    this.KENNR.Equals(input.KENNR))
                ) && 
                (
                    this.M_ROW == input.M_ROW ||
                    (this.M_ROW != null &&
                    this.M_ROW.Equals(input.M_ROW))
                ) && 
                (
                    this.WIRKNR == input.WIRKNR ||
                    (this.WIRKNR != null &&
                    this.WIRKNR.Equals(input.WIRKNR))
                ) && 
                (
                    this.WIRKVAR == input.WIRKVAR ||
                    (this.WIRKVAR != null &&
                    this.WIRKVAR.Equals(input.WIRKVAR))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GEHALT_BIO != null)
                    hashCode = hashCode * 59 + this.GEHALT_BIO.GetHashCode();
                if (this.GEHALT_BIO_EINHEIT != null)
                    hashCode = hashCode * 59 + this.GEHALT_BIO_EINHEIT.GetHashCode();
                if (this.GEHALT_EINHEIT != null)
                    hashCode = hashCode * 59 + this.GEHALT_EINHEIT.GetHashCode();
                if (this.GEHALT_REIN != null)
                    hashCode = hashCode * 59 + this.GEHALT_REIN.GetHashCode();
                if (this.GEHALT_REIN_GRUNDSTRUKTUR != null)
                    hashCode = hashCode * 59 + this.GEHALT_REIN_GRUNDSTRUKTUR.GetHashCode();
                if (this.KENNR != null)
                    hashCode = hashCode * 59 + this.KENNR.GetHashCode();
                if (this.M_ROW != null)
                    hashCode = hashCode * 59 + this.M_ROW.GetHashCode();
                if (this.WIRKNR != null)
                    hashCode = hashCode * 59 + this.WIRKNR.GetHashCode();
                if (this.WIRKVAR != null)
                    hashCode = hashCode * 59 + this.WIRKVAR.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
