// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using REX_APICall;
//
//    var data = Data.FromJson(jsonString);

namespace APICrawlerCall
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Data
    {
        [JsonProperty("info", NullValueHandling = NullValueHandling.Ignore)]
        public Info Info { get; set; }

        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public List<Visits> Visits { get; set; }
    }

    public partial class Visits
    {
        [JsonProperty("visit_id", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        [Key]
        public long? VisitId { get; set; }


        [JsonProperty("location_id", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
  
        public long? LocationId { get; set; }

        [JsonProperty("qc_status", NullValueHandling = NullValueHandling.Ignore)]
        public string QcStatus { get; set; }


        [JsonProperty("location_external_id", NullValueHandling = NullValueHandling.Ignore)]
        public string LocationExternalId { get; set; }

        [JsonProperty("plannings_id", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? PlanningsId { get; set; }

        [JsonProperty("user_id", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? UserId { get; set; }

        [JsonProperty("user_external_id", NullValueHandling = NullValueHandling.Ignore)]
        public string UserExternalId { get; set; }

        [JsonProperty("updated_at", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? UpdatedAt { get; set; }

        [JsonProperty("check_in_time", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? CheckInTime { get; set; }

        [JsonProperty("check_out_time", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? CheckOutTime { get; set; }

        [JsonProperty("project_id", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? ProjectId { get; set; }

        [JsonProperty("campaign_id", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? CampaignId { get; set; }

        [JsonProperty("sets", NullValueHandling = NullValueHandling.Ignore)]
        public List<Set> Sets { get; set; }
    }

    public partial class Set
    {
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
     
        public long SetId { get; set; }

        [JsonProperty("checklist_item_type", NullValueHandling = NullValueHandling.Ignore)]
        public string ChecklistItemType { get; set; }

        [JsonProperty("unit_id")]
        public long? UnitId { get; set; }

        [JsonProperty("unit_external_id")]
        public object UnitExternalId { get; set; }

        [JsonProperty("unit_list_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? UnitListId { get; set; }

        [JsonProperty("unit_type_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? UnitTypeId { get; set; }

        [JsonProperty("unit_had_issue")]
        public long? UnitHadIssue { get; set; }

        [JsonProperty("unit_final_status")]
        public string UnitFinalStatus { get; set; }

        [JsonProperty("parent_response_set_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? ParentResponseSetId { get; set; }

        [JsonProperty("activity_id", NullValueHandling = NullValueHandling.Ignore)]
        public long? ActivityId { get; set; }

        [JsonProperty("responses", NullValueHandling = NullValueHandling.Ignore)]
        public List<SetResponse> SetResponses { get; set; }
    }

    public partial class SetResponse
    {
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        
        public long Id { get; set; }

        [JsonProperty("sub_id")]
        public long? SubId { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }

        [JsonProperty("value_id")]
        public string ValueId { get; set; }
    }


    public enum QcStatus { Accepted, Open, Rejected };

    public enum ChecklistItemType { Flow, Form, UnitFlow };

    public enum UnitFinalStatus { Fixforfuture, Notfixed, Ok };

    public partial struct Value
    {
        public long? Integer;
        public string String;

        public static implicit operator Value(long Integer) => new Value { Integer = Integer };
        public static implicit operator Value(string String) => new Value { String = String };
        public bool IsNull => Integer == null && String == null;
    }

    public partial class Data
    {
        public static Data FromJson(string json) => JsonConvert.DeserializeObject<Data>(json, Converter.Settings);
    }

  
    internal class QcStatusConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(QcStatus) || t == typeof(QcStatus?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "accepted":
                    return QcStatus.Accepted;
                case "open":
                    return QcStatus.Open;
                case "rejected":
                    return QcStatus.Rejected;
            }
            throw new Exception("Cannot unmarshal type QcStatus");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (QcStatus)untypedValue;
            switch (value)
            {
                case QcStatus.Accepted:
                    serializer.Serialize(writer, "accepted");
                    return;
                case QcStatus.Open:
                    serializer.Serialize(writer, "open");
                    return;
                case QcStatus.Rejected:
                    serializer.Serialize(writer, "rejected");
                    return;
            }
            throw new Exception("Cannot marshal type QcStatus");
        }

        public static readonly QcStatusConverter Singleton = new QcStatusConverter();
    }

    internal class ChecklistItemTypeConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(ChecklistItemType) || t == typeof(ChecklistItemType?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "flow":
                    return ChecklistItemType.Flow;
                case "form":
                    return ChecklistItemType.Form;
                case "unit_flow":
                    return ChecklistItemType.UnitFlow;
               
            }
            throw new Exception("Cannot unmarshal type ChecklistItemType");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (ChecklistItemType)untypedValue;
            switch (value)
            {
                case ChecklistItemType.Flow:
                    serializer.Serialize(writer, "flow");
                    return;
                case ChecklistItemType.Form:
                    serializer.Serialize(writer, "form");
                    return;
                case ChecklistItemType.UnitFlow:
                    serializer.Serialize(writer, "unit_flow");
                    return;
            }
            throw new Exception("Cannot marshal type ChecklistItemType");
        }

        public static readonly ChecklistItemTypeConverter Singleton = new ChecklistItemTypeConverter();
    }

    internal class ValueConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Value) || t == typeof(Value?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.Null:
                    return new Value { };
                case JsonToken.Integer:
                    var integerValue = serializer.Deserialize<long>(reader);
                    return new Value { Integer = integerValue };
                case JsonToken.String:
                case JsonToken.Date:
                    var stringValue = serializer.Deserialize<string>(reader);
                    return new Value { String = stringValue };
            }
            throw new Exception("Cannot unmarshal type Value");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (Value)untypedValue;
            if (value.IsNull)
            {
                serializer.Serialize(writer, null);
                return;
            }
            if (value.Integer != null)
            {
                serializer.Serialize(writer, value.Integer.Value);
                return;
            }
            if (value.String != null)
            {
                serializer.Serialize(writer, value.String);
                return;
            }
            throw new Exception("Cannot marshal type Value");
        }

        public static readonly ValueConverter Singleton = new ValueConverter();
    }

    internal class UnitFinalStatusConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(UnitFinalStatus) || t == typeof(UnitFinalStatus?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "fixforfuture":
                    return UnitFinalStatus.Fixforfuture;
                case "notfixed":
                    return UnitFinalStatus.Notfixed;
                case "ok":
                    return UnitFinalStatus.Ok;
            }
            throw new Exception("Cannot unmarshal type UnitFinalStatus");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (UnitFinalStatus)untypedValue;
            switch (value)
            {
                case UnitFinalStatus.Fixforfuture:
                    serializer.Serialize(writer, "fixforfuture");
                    return;
                case UnitFinalStatus.Notfixed:
                    serializer.Serialize(writer, "notfixed");
                    return;
                case UnitFinalStatus.Ok:
                    serializer.Serialize(writer, "ok");
                    return;
            }
            throw new Exception("Cannot marshal type UnitFinalStatus");
        }

        public static readonly UnitFinalStatusConverter Singleton = new UnitFinalStatusConverter();
    }
}
