/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AdresseItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdresseItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdresseItems
        //private AdresseItems instance;

        public AdresseItemsTests()
        {
            // TODO uncomment below to create an instance of AdresseItems
            //instance = new AdresseItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdresseItems
        /// </summary>
        [Fact]
        public void AdresseItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdresseItems
            //Assert.IsType<AdresseItems>(instance);
        }


        /// <summary>
        /// Test the property 'ADRESSE_NR'
        /// </summary>
        [Fact]
        public void ADRESSE_NRTest()
        {
            // TODO unit test for the property 'ADRESSE_NR'
        }
        /// <summary>
        /// Test the property 'ANSCHRIFT1'
        /// </summary>
        [Fact]
        public void ANSCHRIFT1Test()
        {
            // TODO unit test for the property 'ANSCHRIFT1'
        }
        /// <summary>
        /// Test the property 'ANSCHRIFT2'
        /// </summary>
        [Fact]
        public void ANSCHRIFT2Test()
        {
            // TODO unit test for the property 'ANSCHRIFT2'
        }
        /// <summary>
        /// Test the property 'ANSCHRIFT3'
        /// </summary>
        [Fact]
        public void ANSCHRIFT3Test()
        {
            // TODO unit test for the property 'ANSCHRIFT3'
        }
        /// <summary>
        /// Test the property 'ANSCHRIFT4'
        /// </summary>
        [Fact]
        public void ANSCHRIFT4Test()
        {
            // TODO unit test for the property 'ANSCHRIFT4'
        }
        /// <summary>
        /// Test the property 'ANSCHRIFT5'
        /// </summary>
        [Fact]
        public void ANSCHRIFT5Test()
        {
            // TODO unit test for the property 'ANSCHRIFT5'
        }
        /// <summary>
        /// Test the property 'ANSCHRIFT6'
        /// </summary>
        [Fact]
        public void ANSCHRIFT6Test()
        {
            // TODO unit test for the property 'ANSCHRIFT6'
        }
        /// <summary>
        /// Test the property 'ANSPRECHPARTNER'
        /// </summary>
        [Fact]
        public void ANSPRECHPARTNERTest()
        {
            // TODO unit test for the property 'ANSPRECHPARTNER'
        }
        /// <summary>
        /// Test the property 'E_MAIL'
        /// </summary>
        [Fact]
        public void E_MAILTest()
        {
            // TODO unit test for the property 'E_MAIL'
        }
        /// <summary>
        /// Test the property 'FAX'
        /// </summary>
        [Fact]
        public void FAXTest()
        {
            // TODO unit test for the property 'FAX'
        }
        /// <summary>
        /// Test the property 'FIRMA'
        /// </summary>
        [Fact]
        public void FIRMATest()
        {
            // TODO unit test for the property 'FIRMA'
        }
        /// <summary>
        /// Test the property 'FIRMENNAME'
        /// </summary>
        [Fact]
        public void FIRMENNAMETest()
        {
            // TODO unit test for the property 'FIRMENNAME'
        }
        /// <summary>
        /// Test the property 'LAND'
        /// </summary>
        [Fact]
        public void LANDTest()
        {
            // TODO unit test for the property 'LAND'
        }
        /// <summary>
        /// Test the property 'TELEFON'
        /// </summary>
        [Fact]
        public void TELEFONTest()
        {
            // TODO unit test for the property 'TELEFON'
        }

    }

}
