/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AntragItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AntragItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AntragItems
        //private AntragItems instance;

        public AntragItemsTests()
        {
            // TODO uncomment below to create an instance of AntragItems
            //instance = new AntragItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AntragItems
        /// </summary>
        [Fact]
        public void AntragItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AntragItems
            //Assert.IsType<AntragItems>(instance);
        }


        /// <summary>
        /// Test the property 'ANTRAGNR'
        /// </summary>
        [Fact]
        public void ANTRAGNRTest()
        {
            // TODO unit test for the property 'ANTRAGNR'
        }
        /// <summary>
        /// Test the property 'ANTRAGSTELLER'
        /// </summary>
        [Fact]
        public void ANTRAGSTELLERTest()
        {
            // TODO unit test for the property 'ANTRAGSTELLER'
        }
        /// <summary>
        /// Test the property 'ANTRAGSTELLER_NR'
        /// </summary>
        [Fact]
        public void ANTRAGSTELLER_NRTest()
        {
            // TODO unit test for the property 'ANTRAGSTELLER_NR'
        }
        /// <summary>
        /// Test the property 'KENNR'
        /// </summary>
        [Fact]
        public void KENNRTest()
        {
            // TODO unit test for the property 'KENNR'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }

    }

}
