/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AuflagenItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuflagenItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuflagenItems
        //private AuflagenItems instance;

        public AuflagenItemsTests()
        {
            // TODO uncomment below to create an instance of AuflagenItems
            //instance = new AuflagenItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuflagenItems
        /// </summary>
        [Fact]
        public void AuflagenItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuflagenItems
            //Assert.IsType<AuflagenItems>(instance);
        }


        /// <summary>
        /// Test the property 'ABSTAND'
        /// </summary>
        [Fact]
        public void ABSTANDTest()
        {
            // TODO unit test for the property 'ABSTAND'
        }
        /// <summary>
        /// Test the property 'ANWENDBEST'
        /// </summary>
        [Fact]
        public void ANWENDBESTTest()
        {
            // TODO unit test for the property 'ANWENDBEST'
        }
        /// <summary>
        /// Test the property 'ANWENDUNGSTECHNIK'
        /// </summary>
        [Fact]
        public void ANWENDUNGSTECHNIKTest()
        {
            // TODO unit test for the property 'ANWENDUNGSTECHNIK'
        }
        /// <summary>
        /// Test the property 'AUFLAGE'
        /// </summary>
        [Fact]
        public void AUFLAGETest()
        {
            // TODO unit test for the property 'AUFLAGE'
        }
        /// <summary>
        /// Test the property 'AUFLAGENR'
        /// </summary>
        [Fact]
        public void AUFLAGENRTest()
        {
            // TODO unit test for the property 'AUFLAGENR'
        }
        /// <summary>
        /// Test the property 'EBENE'
        /// </summary>
        [Fact]
        public void EBENETest()
        {
            // TODO unit test for the property 'EBENE'
        }
        /// <summary>
        /// Test the property 'KULTUR'
        /// </summary>
        [Fact]
        public void KULTURTest()
        {
            // TODO unit test for the property 'KULTUR'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'REDU_ABSTAND'
        /// </summary>
        [Fact]
        public void REDU_ABSTANDTest()
        {
            // TODO unit test for the property 'REDU_ABSTAND'
        }
        /// <summary>
        /// Test the property 'WEITERE_BEDINGUNG'
        /// </summary>
        [Fact]
        public void WEITERE_BEDINGUNGTest()
        {
            // TODO unit test for the property 'WEITERE_BEDINGUNG'
        }

    }

}
