/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AuflageReduItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuflageReduItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuflageReduItems
        //private AuflageReduItems instance;

        public AuflageReduItemsTests()
        {
            // TODO uncomment below to create an instance of AuflageReduItems
            //instance = new AuflageReduItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuflageReduItems
        /// </summary>
        [Fact]
        public void AuflageReduItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuflageReduItems
            //Assert.IsType<AuflageReduItems>(instance);
        }


        /// <summary>
        /// Test the property 'AUFLAGENR'
        /// </summary>
        [Fact]
        public void AUFLAGENRTest()
        {
            // TODO unit test for the property 'AUFLAGENR'
        }
        /// <summary>
        /// Test the property 'KATEGORIE'
        /// </summary>
        [Fact]
        public void KATEGORIETest()
        {
            // TODO unit test for the property 'KATEGORIE'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'REDU_ABSTAND'
        /// </summary>
        [Fact]
        public void REDU_ABSTANDTest()
        {
            // TODO unit test for the property 'REDU_ABSTAND'
        }

    }

}
