/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AwgAufwandItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AwgAufwandItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AwgAufwandItems
        //private AwgAufwandItems instance;

        public AwgAufwandItemsTests()
        {
            // TODO uncomment below to create an instance of AwgAufwandItems
            //instance = new AwgAufwandItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AwgAufwandItems
        /// </summary>
        [Fact]
        public void AwgAufwandItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AwgAufwandItems
            //Assert.IsType<AwgAufwandItems>(instance);
        }


        /// <summary>
        /// Test the property 'AUFWANDBEDINGUNG'
        /// </summary>
        [Fact]
        public void AUFWANDBEDINGUNGTest()
        {
            // TODO unit test for the property 'AUFWANDBEDINGUNG'
        }
        /// <summary>
        /// Test the property 'AWG_ID'
        /// </summary>
        [Fact]
        public void AWG_IDTest()
        {
            // TODO unit test for the property 'AWG_ID'
        }
        /// <summary>
        /// Test the property 'M_AUFWAND'
        /// </summary>
        [Fact]
        public void M_AUFWANDTest()
        {
            // TODO unit test for the property 'M_AUFWAND'
        }
        /// <summary>
        /// Test the property 'M_AUFWAND_EINHEIT'
        /// </summary>
        [Fact]
        public void M_AUFWAND_EINHEITTest()
        {
            // TODO unit test for the property 'M_AUFWAND_EINHEIT'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'SORTIER_NR'
        /// </summary>
        [Fact]
        public void SORTIER_NRTest()
        {
            // TODO unit test for the property 'SORTIER_NR'
        }
        /// <summary>
        /// Test the property 'W_AUFWAND_BIS'
        /// </summary>
        [Fact]
        public void W_AUFWAND_BISTest()
        {
            // TODO unit test for the property 'W_AUFWAND_BIS'
        }
        /// <summary>
        /// Test the property 'W_AUFWAND_EINHEIT'
        /// </summary>
        [Fact]
        public void W_AUFWAND_EINHEITTest()
        {
            // TODO unit test for the property 'W_AUFWAND_EINHEIT'
        }
        /// <summary>
        /// Test the property 'W_AUFWAND_VON'
        /// </summary>
        [Fact]
        public void W_AUFWAND_VONTest()
        {
            // TODO unit test for the property 'W_AUFWAND_VON'
        }

    }

}
