/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AwgItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AwgItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AwgItems
        //private AwgItems instance;

        public AwgItemsTests()
        {
            // TODO uncomment below to create an instance of AwgItems
            //instance = new AwgItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AwgItems
        /// </summary>
        [Fact]
        public void AwgItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AwgItems
            //Assert.IsType<AwgItems>(instance);
        }


        /// <summary>
        /// Test the property 'ANTRAGNR'
        /// </summary>
        [Fact]
        public void ANTRAGNRTest()
        {
            // TODO unit test for the property 'ANTRAGNR'
        }
        /// <summary>
        /// Test the property 'ANWENDUNGEN_ANZ_JE_BEFALL'
        /// </summary>
        [Fact]
        public void ANWENDUNGEN_ANZ_JE_BEFALLTest()
        {
            // TODO unit test for the property 'ANWENDUNGEN_ANZ_JE_BEFALL'
        }
        /// <summary>
        /// Test the property 'ANWENDUNGEN_MAX_JE_KULTUR'
        /// </summary>
        [Fact]
        public void ANWENDUNGEN_MAX_JE_KULTURTest()
        {
            // TODO unit test for the property 'ANWENDUNGEN_MAX_JE_KULTUR'
        }
        /// <summary>
        /// Test the property 'ANWENDUNGEN_MAX_JE_VEGETATION'
        /// </summary>
        [Fact]
        public void ANWENDUNGEN_MAX_JE_VEGETATIONTest()
        {
            // TODO unit test for the property 'ANWENDUNGEN_MAX_JE_VEGETATION'
        }
        /// <summary>
        /// Test the property 'ANWENDUNGSBEREICH'
        /// </summary>
        [Fact]
        public void ANWENDUNGSBEREICHTest()
        {
            // TODO unit test for the property 'ANWENDUNGSBEREICH'
        }
        /// <summary>
        /// Test the property 'ANWENDUNGSTECHNIK'
        /// </summary>
        [Fact]
        public void ANWENDUNGSTECHNIKTest()
        {
            // TODO unit test for the property 'ANWENDUNGSTECHNIK'
        }
        /// <summary>
        /// Test the property 'AWGNR'
        /// </summary>
        [Fact]
        public void AWGNRTest()
        {
            // TODO unit test for the property 'AWGNR'
        }
        /// <summary>
        /// Test the property 'AWG_ID'
        /// </summary>
        [Fact]
        public void AWG_IDTest()
        {
            // TODO unit test for the property 'AWG_ID'
        }
        /// <summary>
        /// Test the property 'AW_ABSTAND_BIS'
        /// </summary>
        [Fact]
        public void AW_ABSTAND_BISTest()
        {
            // TODO unit test for the property 'AW_ABSTAND_BIS'
        }
        /// <summary>
        /// Test the property 'AW_ABSTAND_EINHEIT'
        /// </summary>
        [Fact]
        public void AW_ABSTAND_EINHEITTest()
        {
            // TODO unit test for the property 'AW_ABSTAND_EINHEIT'
        }
        /// <summary>
        /// Test the property 'AW_ABSTAND_VON'
        /// </summary>
        [Fact]
        public void AW_ABSTAND_VONTest()
        {
            // TODO unit test for the property 'AW_ABSTAND_VON'
        }
        /// <summary>
        /// Test the property 'EINSATZGEBIET'
        /// </summary>
        [Fact]
        public void EINSATZGEBIETTest()
        {
            // TODO unit test for the property 'EINSATZGEBIET'
        }
        /// <summary>
        /// Test the property 'GENEHMIGUNG'
        /// </summary>
        [Fact]
        public void GENEHMIGUNGTest()
        {
            // TODO unit test for the property 'GENEHMIGUNG'
        }
        /// <summary>
        /// Test the property 'HUK'
        /// </summary>
        [Fact]
        public void HUKTest()
        {
            // TODO unit test for the property 'HUK'
        }
        /// <summary>
        /// Test the property 'KENNR'
        /// </summary>
        [Fact]
        public void KENNRTest()
        {
            // TODO unit test for the property 'KENNR'
        }
        /// <summary>
        /// Test the property 'KULTUR_ERL'
        /// </summary>
        [Fact]
        public void KULTUR_ERLTest()
        {
            // TODO unit test for the property 'KULTUR_ERL'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'SCHADORG_ERL'
        /// </summary>
        [Fact]
        public void SCHADORG_ERLTest()
        {
            // TODO unit test for the property 'SCHADORG_ERL'
        }
        /// <summary>
        /// Test the property 'STADIUM_KULTUR_BEM'
        /// </summary>
        [Fact]
        public void STADIUM_KULTUR_BEMTest()
        {
            // TODO unit test for the property 'STADIUM_KULTUR_BEM'
        }
        /// <summary>
        /// Test the property 'STADIUM_KULTUR_BIS'
        /// </summary>
        [Fact]
        public void STADIUM_KULTUR_BISTest()
        {
            // TODO unit test for the property 'STADIUM_KULTUR_BIS'
        }
        /// <summary>
        /// Test the property 'STADIUM_KULTUR_KODELISTE'
        /// </summary>
        [Fact]
        public void STADIUM_KULTUR_KODELISTETest()
        {
            // TODO unit test for the property 'STADIUM_KULTUR_KODELISTE'
        }
        /// <summary>
        /// Test the property 'STADIUM_KULTUR_VON'
        /// </summary>
        [Fact]
        public void STADIUM_KULTUR_VONTest()
        {
            // TODO unit test for the property 'STADIUM_KULTUR_VON'
        }
        /// <summary>
        /// Test the property 'STADIUM_SCHADORG_BEM'
        /// </summary>
        [Fact]
        public void STADIUM_SCHADORG_BEMTest()
        {
            // TODO unit test for the property 'STADIUM_SCHADORG_BEM'
        }
        /// <summary>
        /// Test the property 'STADIUM_SCHADORG_BIS'
        /// </summary>
        [Fact]
        public void STADIUM_SCHADORG_BISTest()
        {
            // TODO unit test for the property 'STADIUM_SCHADORG_BIS'
        }
        /// <summary>
        /// Test the property 'STADIUM_SCHADORG_KODELISTE'
        /// </summary>
        [Fact]
        public void STADIUM_SCHADORG_KODELISTETest()
        {
            // TODO unit test for the property 'STADIUM_SCHADORG_KODELISTE'
        }
        /// <summary>
        /// Test the property 'STADIUM_SCHADORG_VON'
        /// </summary>
        [Fact]
        public void STADIUM_SCHADORG_VONTest()
        {
            // TODO unit test for the property 'STADIUM_SCHADORG_VON'
        }
        /// <summary>
        /// Test the property 'WIRKUNGSBEREICH'
        /// </summary>
        [Fact]
        public void WIRKUNGSBEREICHTest()
        {
            // TODO unit test for the property 'WIRKUNGSBEREICH'
        }

    }

}
