/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AwgKulturItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AwgKulturItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AwgKulturItems
        //private AwgKulturItems instance;

        public AwgKulturItemsTests()
        {
            // TODO uncomment below to create an instance of AwgKulturItems
            //instance = new AwgKulturItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AwgKulturItems
        /// </summary>
        [Fact]
        public void AwgKulturItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AwgKulturItems
            //Assert.IsType<AwgKulturItems>(instance);
        }


        /// <summary>
        /// Test the property 'AUSGENOMMEN'
        /// </summary>
        [Fact]
        public void AUSGENOMMENTest()
        {
            // TODO unit test for the property 'AUSGENOMMEN'
        }
        /// <summary>
        /// Test the property 'AWG_ID'
        /// </summary>
        [Fact]
        public void AWG_IDTest()
        {
            // TODO unit test for the property 'AWG_ID'
        }
        /// <summary>
        /// Test the property 'KULTUR'
        /// </summary>
        [Fact]
        public void KULTURTest()
        {
            // TODO unit test for the property 'KULTUR'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'SORTIER_NR'
        /// </summary>
        [Fact]
        public void SORTIER_NRTest()
        {
            // TODO unit test for the property 'SORTIER_NR'
        }

    }

}
