/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AwgPartnerItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AwgPartnerItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AwgPartnerItems
        //private AwgPartnerItems instance;

        public AwgPartnerItemsTests()
        {
            // TODO uncomment below to create an instance of AwgPartnerItems
            //instance = new AwgPartnerItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AwgPartnerItems
        /// </summary>
        [Fact]
        public void AwgPartnerItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AwgPartnerItems
            //Assert.IsType<AwgPartnerItems>(instance);
        }


        /// <summary>
        /// Test the property 'AWG_ID'
        /// </summary>
        [Fact]
        public void AWG_IDTest()
        {
            // TODO unit test for the property 'AWG_ID'
        }
        /// <summary>
        /// Test the property 'MISCHUNG_ART'
        /// </summary>
        [Fact]
        public void MISCHUNG_ARTTest()
        {
            // TODO unit test for the property 'MISCHUNG_ART'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'PARTNER_KENNR'
        /// </summary>
        [Fact]
        public void PARTNER_KENNRTest()
        {
            // TODO unit test for the property 'PARTNER_KENNR'
        }

    }

}
