/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AwgPartnerAufwandItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AwgPartnerAufwandItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AwgPartnerAufwandItems
        //private AwgPartnerAufwandItems instance;

        public AwgPartnerAufwandItemsTests()
        {
            // TODO uncomment below to create an instance of AwgPartnerAufwandItems
            //instance = new AwgPartnerAufwandItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AwgPartnerAufwandItems
        /// </summary>
        [Fact]
        public void AwgPartnerAufwandItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AwgPartnerAufwandItems
            //Assert.IsType<AwgPartnerAufwandItems>(instance);
        }


        /// <summary>
        /// Test the property 'AUFWANDBEDINGUNG'
        /// </summary>
        [Fact]
        public void AUFWANDBEDINGUNGTest()
        {
            // TODO unit test for the property 'AUFWANDBEDINGUNG'
        }
        /// <summary>
        /// Test the property 'AWG_ID'
        /// </summary>
        [Fact]
        public void AWG_IDTest()
        {
            // TODO unit test for the property 'AWG_ID'
        }
        /// <summary>
        /// Test the property 'M_AUFWAND'
        /// </summary>
        [Fact]
        public void M_AUFWANDTest()
        {
            // TODO unit test for the property 'M_AUFWAND'
        }
        /// <summary>
        /// Test the property 'M_AUFWAND_EINHEIT'
        /// </summary>
        [Fact]
        public void M_AUFWAND_EINHEITTest()
        {
            // TODO unit test for the property 'M_AUFWAND_EINHEIT'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'PARTNER_KENNR'
        /// </summary>
        [Fact]
        public void PARTNER_KENNRTest()
        {
            // TODO unit test for the property 'PARTNER_KENNR'
        }

    }

}
