/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AwgVerwendungszweckItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AwgVerwendungszweckItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AwgVerwendungszweckItems
        //private AwgVerwendungszweckItems instance;

        public AwgVerwendungszweckItemsTests()
        {
            // TODO uncomment below to create an instance of AwgVerwendungszweckItems
            //instance = new AwgVerwendungszweckItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AwgVerwendungszweckItems
        /// </summary>
        [Fact]
        public void AwgVerwendungszweckItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AwgVerwendungszweckItems
            //Assert.IsType<AwgVerwendungszweckItems>(instance);
        }


        /// <summary>
        /// Test the property 'AWG_ID'
        /// </summary>
        [Fact]
        public void AWG_IDTest()
        {
            // TODO unit test for the property 'AWG_ID'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'VERWENDUNGSZWECK'
        /// </summary>
        [Fact]
        public void VERWENDUNGSZWECKTest()
        {
            // TODO unit test for the property 'VERWENDUNGSZWECK'
        }

    }

}
