/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AwgWartezeitAusgKulturItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AwgWartezeitAusgKulturItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AwgWartezeitAusgKulturItems
        //private AwgWartezeitAusgKulturItems instance;

        public AwgWartezeitAusgKulturItemsTests()
        {
            // TODO uncomment below to create an instance of AwgWartezeitAusgKulturItems
            //instance = new AwgWartezeitAusgKulturItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AwgWartezeitAusgKulturItems
        /// </summary>
        [Fact]
        public void AwgWartezeitAusgKulturItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AwgWartezeitAusgKulturItems
            //Assert.IsType<AwgWartezeitAusgKulturItems>(instance);
        }


        /// <summary>
        /// Test the property 'AWG_WARTEZEIT_NR'
        /// </summary>
        [Fact]
        public void AWG_WARTEZEIT_NRTest()
        {
            // TODO unit test for the property 'AWG_WARTEZEIT_NR'
        }
        /// <summary>
        /// Test the property 'KULTUR'
        /// </summary>
        [Fact]
        public void KULTURTest()
        {
            // TODO unit test for the property 'KULTUR'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }

    }

}
