/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AwgWartezeitAusgKultur
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AwgWartezeitAusgKulturTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AwgWartezeitAusgKultur
        //private AwgWartezeitAusgKultur instance;

        public AwgWartezeitAusgKulturTests()
        {
            // TODO uncomment below to create an instance of AwgWartezeitAusgKultur
            //instance = new AwgWartezeitAusgKultur();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AwgWartezeitAusgKultur
        /// </summary>
        [Fact]
        public void AwgWartezeitAusgKulturInstanceTest()
        {
            // TODO uncomment below to test "IsType" AwgWartezeitAusgKultur
            //Assert.IsType<AwgWartezeitAusgKultur>(instance);
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

    }

}
