/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AwgWartezeitItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AwgWartezeitItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AwgWartezeitItems
        //private AwgWartezeitItems instance;

        public AwgWartezeitItemsTests()
        {
            // TODO uncomment below to create an instance of AwgWartezeitItems
            //instance = new AwgWartezeitItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AwgWartezeitItems
        /// </summary>
        [Fact]
        public void AwgWartezeitItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AwgWartezeitItems
            //Assert.IsType<AwgWartezeitItems>(instance);
        }


        /// <summary>
        /// Test the property 'ANWENDUNGSBEREICH'
        /// </summary>
        [Fact]
        public void ANWENDUNGSBEREICHTest()
        {
            // TODO unit test for the property 'ANWENDUNGSBEREICH'
        }
        /// <summary>
        /// Test the property 'AWG_ID'
        /// </summary>
        [Fact]
        public void AWG_IDTest()
        {
            // TODO unit test for the property 'AWG_ID'
        }
        /// <summary>
        /// Test the property 'AWG_WARTEZEIT_NR'
        /// </summary>
        [Fact]
        public void AWG_WARTEZEIT_NRTest()
        {
            // TODO unit test for the property 'AWG_WARTEZEIT_NR'
        }
        /// <summary>
        /// Test the property 'ERLAEUTERUNG'
        /// </summary>
        [Fact]
        public void ERLAEUTERUNGTest()
        {
            // TODO unit test for the property 'ERLAEUTERUNG'
        }
        /// <summary>
        /// Test the property 'GESETZT_WARTEZEIT'
        /// </summary>
        [Fact]
        public void GESETZT_WARTEZEITTest()
        {
            // TODO unit test for the property 'GESETZT_WARTEZEIT'
        }
        /// <summary>
        /// Test the property 'GESETZT_WARTEZEIT_BEM'
        /// </summary>
        [Fact]
        public void GESETZT_WARTEZEIT_BEMTest()
        {
            // TODO unit test for the property 'GESETZT_WARTEZEIT_BEM'
        }
        /// <summary>
        /// Test the property 'KULTUR'
        /// </summary>
        [Fact]
        public void KULTURTest()
        {
            // TODO unit test for the property 'KULTUR'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'SORTIER_NR'
        /// </summary>
        [Fact]
        public void SORTIER_NRTest()
        {
            // TODO unit test for the property 'SORTIER_NR'
        }

    }

}
