/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AwgZeitpunktItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AwgZeitpunktItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AwgZeitpunktItems
        //private AwgZeitpunktItems instance;

        public AwgZeitpunktItemsTests()
        {
            // TODO uncomment below to create an instance of AwgZeitpunktItems
            //instance = new AwgZeitpunktItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AwgZeitpunktItems
        /// </summary>
        [Fact]
        public void AwgZeitpunktItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AwgZeitpunktItems
            //Assert.IsType<AwgZeitpunktItems>(instance);
        }


        /// <summary>
        /// Test the property 'AWG_ID'
        /// </summary>
        [Fact]
        public void AWG_IDTest()
        {
            // TODO unit test for the property 'AWG_ID'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'OPERAND_ZU_VORHER'
        /// </summary>
        [Fact]
        public void OPERAND_ZU_VORHERTest()
        {
            // TODO unit test for the property 'OPERAND_ZU_VORHER'
        }
        /// <summary>
        /// Test the property 'SORTIER_NR'
        /// </summary>
        [Fact]
        public void SORTIER_NRTest()
        {
            // TODO unit test for the property 'SORTIER_NR'
        }
        /// <summary>
        /// Test the property 'ZEITPUNKT'
        /// </summary>
        [Fact]
        public void ZEITPUNKTTest()
        {
            // TODO unit test for the property 'ZEITPUNKT'
        }

    }

}
