/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing GhsSicherheitshinweiseItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GhsSicherheitshinweiseItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GhsSicherheitshinweiseItems
        //private GhsSicherheitshinweiseItems instance;

        public GhsSicherheitshinweiseItemsTests()
        {
            // TODO uncomment below to create an instance of GhsSicherheitshinweiseItems
            //instance = new GhsSicherheitshinweiseItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GhsSicherheitshinweiseItems
        /// </summary>
        [Fact]
        public void GhsSicherheitshinweiseItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" GhsSicherheitshinweiseItems
            //Assert.IsType<GhsSicherheitshinweiseItems>(instance);
        }


        /// <summary>
        /// Test the property 'KENNR'
        /// </summary>
        [Fact]
        public void KENNRTest()
        {
            // TODO unit test for the property 'KENNR'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'SICHERHEITSHINWEIS'
        /// </summary>
        [Fact]
        public void SICHERHEITSHINWEISTest()
        {
            // TODO unit test for the property 'SICHERHEITSHINWEIS'
        }

    }

}
