/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing HinweisItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HinweisItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HinweisItems
        //private HinweisItems instance;

        public HinweisItemsTests()
        {
            // TODO uncomment below to create an instance of HinweisItems
            //instance = new HinweisItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HinweisItems
        /// </summary>
        [Fact]
        public void HinweisItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" HinweisItems
            //Assert.IsType<HinweisItems>(instance);
        }


        /// <summary>
        /// Test the property 'EBENE'
        /// </summary>
        [Fact]
        public void EBENETest()
        {
            // TODO unit test for the property 'EBENE'
        }
        /// <summary>
        /// Test the property 'HINWEIS'
        /// </summary>
        [Fact]
        public void HINWEISTest()
        {
            // TODO unit test for the property 'HINWEIS'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }

    }

}
