/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing KodeItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KodeItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KodeItems
        //private KodeItems instance;

        public KodeItemsTests()
        {
            // TODO uncomment below to create an instance of KodeItems
            //instance = new KodeItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KodeItems
        /// </summary>
        [Fact]
        public void KodeItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" KodeItems
            //Assert.IsType<KodeItems>(instance);
        }


        /// <summary>
        /// Test the property 'KODE'
        /// </summary>
        [Fact]
        public void KODETest()
        {
            // TODO unit test for the property 'KODE'
        }
        /// <summary>
        /// Test the property 'KODELISTE'
        /// </summary>
        [Fact]
        public void KODELISTETest()
        {
            // TODO unit test for the property 'KODELISTE'
        }
        /// <summary>
        /// Test the property 'KODETEXT'
        /// </summary>
        [Fact]
        public void KODETEXTTest()
        {
            // TODO unit test for the property 'KODETEXT'
        }
        /// <summary>
        /// Test the property 'SPERRE'
        /// </summary>
        [Fact]
        public void SPERRETest()
        {
            // TODO unit test for the property 'SPERRE'
        }
        /// <summary>
        /// Test the property 'SPRACHE'
        /// </summary>
        [Fact]
        public void SPRACHETest()
        {
            // TODO unit test for the property 'SPRACHE'
        }

    }

}
