/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing KodelisteItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KodelisteItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KodelisteItems
        //private KodelisteItems instance;

        public KodelisteItemsTests()
        {
            // TODO uncomment below to create an instance of KodelisteItems
            //instance = new KodelisteItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KodelisteItems
        /// </summary>
        [Fact]
        public void KodelisteItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" KodelisteItems
            //Assert.IsType<KodelisteItems>(instance);
        }


        /// <summary>
        /// Test the property 'KODELISTE'
        /// </summary>
        [Fact]
        public void KODELISTETest()
        {
            // TODO unit test for the property 'KODELISTE'
        }
        /// <summary>
        /// Test the property 'LISTENNAME'
        /// </summary>
        [Fact]
        public void LISTENNAMETest()
        {
            // TODO unit test for the property 'LISTENNAME'
        }

    }

}
