/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing KodelisteFeldnameItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KodelisteFeldnameItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KodelisteFeldnameItems
        //private KodelisteFeldnameItems instance;

        public KodelisteFeldnameItemsTests()
        {
            // TODO uncomment below to create an instance of KodelisteFeldnameItems
            //instance = new KodelisteFeldnameItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KodelisteFeldnameItems
        /// </summary>
        [Fact]
        public void KodelisteFeldnameItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" KodelisteFeldnameItems
            //Assert.IsType<KodelisteFeldnameItems>(instance);
        }


        /// <summary>
        /// Test the property 'FELDNAME'
        /// </summary>
        [Fact]
        public void FELDNAMETest()
        {
            // TODO unit test for the property 'FELDNAME'
        }
        /// <summary>
        /// Test the property 'KODELISTE'
        /// </summary>
        [Fact]
        public void KODELISTETest()
        {
            // TODO unit test for the property 'KODELISTE'
        }
        /// <summary>
        /// Test the property 'TABELLE'
        /// </summary>
        [Fact]
        public void TABELLETest()
        {
            // TODO unit test for the property 'TABELLE'
        }

    }

}
