/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing KulturGruppeItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KulturGruppeItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KulturGruppeItems
        //private KulturGruppeItems instance;

        public KulturGruppeItemsTests()
        {
            // TODO uncomment below to create an instance of KulturGruppeItems
            //instance = new KulturGruppeItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KulturGruppeItems
        /// </summary>
        [Fact]
        public void KulturGruppeItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" KulturGruppeItems
            //Assert.IsType<KulturGruppeItems>(instance);
        }


        /// <summary>
        /// Test the property 'KULTUR'
        /// </summary>
        [Fact]
        public void KULTURTest()
        {
            // TODO unit test for the property 'KULTUR'
        }
        /// <summary>
        /// Test the property 'KULTUR_GRUPPE'
        /// </summary>
        [Fact]
        public void KULTUR_GRUPPETest()
        {
            // TODO unit test for the property 'KULTUR_GRUPPE'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }

    }

}
