/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MittelAbgelaufenItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MittelAbgelaufenItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MittelAbgelaufenItems
        //private MittelAbgelaufenItems instance;

        public MittelAbgelaufenItemsTests()
        {
            // TODO uncomment below to create an instance of MittelAbgelaufenItems
            //instance = new MittelAbgelaufenItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MittelAbgelaufenItems
        /// </summary>
        [Fact]
        public void MittelAbgelaufenItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" MittelAbgelaufenItems
            //Assert.IsType<MittelAbgelaufenItems>(instance);
        }


        /// <summary>
        /// Test the property 'AUFBRAUCHFRIST'
        /// </summary>
        [Fact]
        public void AUFBRAUCHFRISTTest()
        {
            // TODO unit test for the property 'AUFBRAUCHFRIST'
        }
        /// <summary>
        /// Test the property 'FORMULIERUNG_ART'
        /// </summary>
        [Fact]
        public void FORMULIERUNG_ARTTest()
        {
            // TODO unit test for the property 'FORMULIERUNG_ART'
        }
        /// <summary>
        /// Test the property 'KENNR'
        /// </summary>
        [Fact]
        public void KENNRTest()
        {
            // TODO unit test for the property 'KENNR'
        }
        /// <summary>
        /// Test the property 'MITTELNAME'
        /// </summary>
        [Fact]
        public void MITTELNAMETest()
        {
            // TODO unit test for the property 'MITTELNAME'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'STATUS'
        /// </summary>
        [Fact]
        public void STATUSTest()
        {
            // TODO unit test for the property 'STATUS'
        }
        /// <summary>
        /// Test the property 'ZUL_ENDE'
        /// </summary>
        [Fact]
        public void ZUL_ENDETest()
        {
            // TODO unit test for the property 'ZUL_ENDE'
        }
        /// <summary>
        /// Test the property 'ZUL_ERSTMALIG_AM'
        /// </summary>
        [Fact]
        public void ZUL_ERSTMALIG_AMTest()
        {
            // TODO unit test for the property 'ZUL_ERSTMALIG_AM'
        }

    }

}
