/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MittelVertriebItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MittelVertriebItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MittelVertriebItems
        //private MittelVertriebItems instance;

        public MittelVertriebItemsTests()
        {
            // TODO uncomment below to create an instance of MittelVertriebItems
            //instance = new MittelVertriebItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MittelVertriebItems
        /// </summary>
        [Fact]
        public void MittelVertriebItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" MittelVertriebItems
            //Assert.IsType<MittelVertriebItems>(instance);
        }


        /// <summary>
        /// Test the property 'KENNR'
        /// </summary>
        [Fact]
        public void KENNRTest()
        {
            // TODO unit test for the property 'KENNR'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'VERTRIEBSFIRMA'
        /// </summary>
        [Fact]
        public void VERTRIEBSFIRMATest()
        {
            // TODO unit test for the property 'VERTRIEBSFIRMA'
        }
        /// <summary>
        /// Test the property 'VERTRIEBSFIRMA_NR'
        /// </summary>
        [Fact]
        public void VERTRIEBSFIRMA_NRTest()
        {
            // TODO unit test for the property 'VERTRIEBSFIRMA_NR'
        }

    }

}
