/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MittelAbpackungItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MittelAbpackungItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MittelAbpackungItems
        //private MittelAbpackungItems instance;

        public MittelAbpackungItemsTests()
        {
            // TODO uncomment below to create an instance of MittelAbpackungItems
            //instance = new MittelAbpackungItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MittelAbpackungItems
        /// </summary>
        [Fact]
        public void MittelAbpackungItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" MittelAbpackungItems
            //Assert.IsType<MittelAbpackungItems>(instance);
        }


        /// <summary>
        /// Test the property 'ANZAHL'
        /// </summary>
        [Fact]
        public void ANZAHLTest()
        {
            // TODO unit test for the property 'ANZAHL'
        }
        /// <summary>
        /// Test the property 'INHALT_EINHEIT'
        /// </summary>
        [Fact]
        public void INHALT_EINHEITTest()
        {
            // TODO unit test for the property 'INHALT_EINHEIT'
        }
        /// <summary>
        /// Test the property 'KENNR'
        /// </summary>
        [Fact]
        public void KENNRTest()
        {
            // TODO unit test for the property 'KENNR'
        }
        /// <summary>
        /// Test the property 'MENGE'
        /// </summary>
        [Fact]
        public void MENGETest()
        {
            // TODO unit test for the property 'MENGE'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'NICHTBERUFLICHE_ANWENDER'
        /// </summary>
        [Fact]
        public void NICHTBERUFLICHE_ANWENDERTest()
        {
            // TODO unit test for the property 'NICHTBERUFLICHE_ANWENDER'
        }
        /// <summary>
        /// Test the property 'VERPACKUNGSART'
        /// </summary>
        [Fact]
        public void VERPACKUNGSARTTest()
        {
            // TODO unit test for the property 'VERPACKUNGSART'
        }
        /// <summary>
        /// Test the property 'VERPACKUNGSMATERIAL'
        /// </summary>
        [Fact]
        public void VERPACKUNGSMATERIALTest()
        {
            // TODO unit test for the property 'VERPACKUNGSMATERIAL'
        }

    }

}
