/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ParallelimportAbgelaufenItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParallelimportAbgelaufenItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ParallelimportAbgelaufenItems
        //private ParallelimportAbgelaufenItems instance;

        public ParallelimportAbgelaufenItemsTests()
        {
            // TODO uncomment below to create an instance of ParallelimportAbgelaufenItems
            //instance = new ParallelimportAbgelaufenItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ParallelimportAbgelaufenItems
        /// </summary>
        [Fact]
        public void ParallelimportAbgelaufenItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ParallelimportAbgelaufenItems
            //Assert.IsType<ParallelimportAbgelaufenItems>(instance);
        }


        /// <summary>
        /// Test the property 'BESCHEID_DATUM'
        /// </summary>
        [Fact]
        public void BESCHEID_DATUMTest()
        {
            // TODO unit test for the property 'BESCHEID_DATUM'
        }
        /// <summary>
        /// Test the property 'BESCHEINIGUNG'
        /// </summary>
        [Fact]
        public void BESCHEINIGUNGTest()
        {
            // TODO unit test for the property 'BESCHEINIGUNG'
        }
        /// <summary>
        /// Test the property 'GUELTIG'
        /// </summary>
        [Fact]
        public void GUELTIGTest()
        {
            // TODO unit test for the property 'GUELTIG'
        }
        /// <summary>
        /// Test the property 'IMPORTEUR'
        /// </summary>
        [Fact]
        public void IMPORTEURTest()
        {
            // TODO unit test for the property 'IMPORTEUR'
        }
        /// <summary>
        /// Test the property 'IMPORTEUR_NR'
        /// </summary>
        [Fact]
        public void IMPORTEUR_NRTest()
        {
            // TODO unit test for the property 'IMPORTEUR_NR'
        }
        /// <summary>
        /// Test the property 'IMPORTEUR_TXT'
        /// </summary>
        [Fact]
        public void IMPORTEUR_TXTTest()
        {
            // TODO unit test for the property 'IMPORTEUR_TXT'
        }
        /// <summary>
        /// Test the property 'MITTELNAME'
        /// </summary>
        [Fact]
        public void MITTELNAMETest()
        {
            // TODO unit test for the property 'MITTELNAME'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'PI_BESCHEIDNR'
        /// </summary>
        [Fact]
        public void PI_BESCHEIDNRTest()
        {
            // TODO unit test for the property 'PI_BESCHEIDNR'
        }
        /// <summary>
        /// Test the property 'PI_KENNZIFFER'
        /// </summary>
        [Fact]
        public void PI_KENNZIFFERTest()
        {
            // TODO unit test for the property 'PI_KENNZIFFER'
        }
        /// <summary>
        /// Test the property 'PI_MITTELNAME'
        /// </summary>
        [Fact]
        public void PI_MITTELNAMETest()
        {
            // TODO unit test for the property 'PI_MITTELNAME'
        }
        /// <summary>
        /// Test the property 'PI_PSMNR'
        /// </summary>
        [Fact]
        public void PI_PSMNRTest()
        {
            // TODO unit test for the property 'PI_PSMNR'
        }
        /// <summary>
        /// Test the property 'PI_REFERENZ_KENNR'
        /// </summary>
        [Fact]
        public void PI_REFERENZ_KENNRTest()
        {
            // TODO unit test for the property 'PI_REFERENZ_KENNR'
        }
        /// <summary>
        /// Test the property 'PI_STATUS'
        /// </summary>
        [Fact]
        public void PI_STATUSTest()
        {
            // TODO unit test for the property 'PI_STATUS'
        }

    }

}
