/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SchadorgGruppeItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchadorgGruppeItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SchadorgGruppeItems
        //private SchadorgGruppeItems instance;

        public SchadorgGruppeItemsTests()
        {
            // TODO uncomment below to create an instance of SchadorgGruppeItems
            //instance = new SchadorgGruppeItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchadorgGruppeItems
        /// </summary>
        [Fact]
        public void SchadorgGruppeItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SchadorgGruppeItems
            //Assert.IsType<SchadorgGruppeItems>(instance);
        }


        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'SCHADORG'
        /// </summary>
        [Fact]
        public void SCHADORGTest()
        {
            // TODO unit test for the property 'SCHADORG'
        }
        /// <summary>
        /// Test the property 'SCHADORG_GRUPPE'
        /// </summary>
        [Fact]
        public void SCHADORG_GRUPPETest()
        {
            // TODO unit test for the property 'SCHADORG_GRUPPE'
        }

    }

}
