/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing StaerkungItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StaerkungItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StaerkungItems
        //private StaerkungItems instance;

        public StaerkungItemsTests()
        {
            // TODO uncomment below to create an instance of StaerkungItems
            //instance = new StaerkungItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StaerkungItems
        /// </summary>
        [Fact]
        public void StaerkungItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" StaerkungItems
            //Assert.IsType<StaerkungItems>(instance);
        }


        /// <summary>
        /// Test the property 'ANTRAGSTELLER'
        /// </summary>
        [Fact]
        public void ANTRAGSTELLERTest()
        {
            // TODO unit test for the property 'ANTRAGSTELLER'
        }
        /// <summary>
        /// Test the property 'ANTRAGSTELLER_NR'
        /// </summary>
        [Fact]
        public void ANTRAGSTELLER_NRTest()
        {
            // TODO unit test for the property 'ANTRAGSTELLER_NR'
        }
        /// <summary>
        /// Test the property 'GENEHMIGUNG_AM'
        /// </summary>
        [Fact]
        public void GENEHMIGUNG_AMTest()
        {
            // TODO unit test for the property 'GENEHMIGUNG_AM'
        }
        /// <summary>
        /// Test the property 'KENNR'
        /// </summary>
        [Fact]
        public void KENNRTest()
        {
            // TODO unit test for the property 'KENNR'
        }
        /// <summary>
        /// Test the property 'MITTELNAME'
        /// </summary>
        [Fact]
        public void MITTELNAMETest()
        {
            // TODO unit test for the property 'MITTELNAME'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }

    }

}
