/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing WirkstoffItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WirkstoffItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WirkstoffItems
        //private WirkstoffItems instance;

        public WirkstoffItemsTests()
        {
            // TODO uncomment below to create an instance of WirkstoffItems
            //instance = new WirkstoffItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WirkstoffItems
        /// </summary>
        [Fact]
        public void WirkstoffItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" WirkstoffItems
            //Assert.IsType<WirkstoffItems>(instance);
        }


        /// <summary>
        /// Test the property 'GENEHMIGT'
        /// </summary>
        [Fact]
        public void GENEHMIGTTest()
        {
            // TODO unit test for the property 'GENEHMIGT'
        }
        /// <summary>
        /// Test the property 'KATEGORIE'
        /// </summary>
        [Fact]
        public void KATEGORIETest()
        {
            // TODO unit test for the property 'KATEGORIE'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'WIRKNR'
        /// </summary>
        [Fact]
        public void WIRKNRTest()
        {
            // TODO unit test for the property 'WIRKNR'
        }
        /// <summary>
        /// Test the property 'WIRKSTOFFNAME'
        /// </summary>
        [Fact]
        public void WIRKSTOFFNAMETest()
        {
            // TODO unit test for the property 'WIRKSTOFFNAME'
        }
        /// <summary>
        /// Test the property 'WIRKSTOFFNAME_EN'
        /// </summary>
        [Fact]
        public void WIRKSTOFFNAME_ENTest()
        {
            // TODO unit test for the property 'WIRKSTOFFNAME_EN'
        }

    }

}
