/*
 * ORDS generated API for api-v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APICrawler.Api.Api;
using APICrawler.Api.Model;
using APICrawler.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace APICrawler.Api.Test.Model
{
    /// <summary>
    ///  Class for testing WirkstoffGehaltItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WirkstoffGehaltItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WirkstoffGehaltItems
        //private WirkstoffGehaltItems instance;

        public WirkstoffGehaltItemsTests()
        {
            // TODO uncomment below to create an instance of WirkstoffGehaltItems
            //instance = new WirkstoffGehaltItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WirkstoffGehaltItems
        /// </summary>
        [Fact]
        public void WirkstoffGehaltItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" WirkstoffGehaltItems
            //Assert.IsType<WirkstoffGehaltItems>(instance);
        }


        /// <summary>
        /// Test the property 'GEHALT_BIO'
        /// </summary>
        [Fact]
        public void GEHALT_BIOTest()
        {
            // TODO unit test for the property 'GEHALT_BIO'
        }
        /// <summary>
        /// Test the property 'GEHALT_BIO_EINHEIT'
        /// </summary>
        [Fact]
        public void GEHALT_BIO_EINHEITTest()
        {
            // TODO unit test for the property 'GEHALT_BIO_EINHEIT'
        }
        /// <summary>
        /// Test the property 'GEHALT_EINHEIT'
        /// </summary>
        [Fact]
        public void GEHALT_EINHEITTest()
        {
            // TODO unit test for the property 'GEHALT_EINHEIT'
        }
        /// <summary>
        /// Test the property 'GEHALT_REIN'
        /// </summary>
        [Fact]
        public void GEHALT_REINTest()
        {
            // TODO unit test for the property 'GEHALT_REIN'
        }
        /// <summary>
        /// Test the property 'GEHALT_REIN_GRUNDSTRUKTUR'
        /// </summary>
        [Fact]
        public void GEHALT_REIN_GRUNDSTRUKTURTest()
        {
            // TODO unit test for the property 'GEHALT_REIN_GRUNDSTRUKTUR'
        }
        /// <summary>
        /// Test the property 'KENNR'
        /// </summary>
        [Fact]
        public void KENNRTest()
        {
            // TODO unit test for the property 'KENNR'
        }
        /// <summary>
        /// Test the property 'M_ROW'
        /// </summary>
        [Fact]
        public void M_ROWTest()
        {
            // TODO unit test for the property 'M_ROW'
        }
        /// <summary>
        /// Test the property 'WIRKNR'
        /// </summary>
        [Fact]
        public void WIRKNRTest()
        {
            // TODO unit test for the property 'WIRKNR'
        }
        /// <summary>
        /// Test the property 'WIRKVAR'
        /// </summary>
        [Fact]
        public void WIRKVARTest()
        {
            // TODO unit test for the property 'WIRKVAR'
        }

    }

}
